### ISSUE TITLE
Your cache is NOT working. Please check the settings in config/app.php

### ISSUE THREAD

**Issue by WilliamHanMinChen** [cakephp/app#1020]
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 5.1.0
* Platform and Target: HTTPD, MACOS

### What you did
Created a CakePHP app from the skeleton via composer create-project

### What happened
The application home page states that there is a cache error. 

### What you expected to happen
There should not be a cache error

Suggested fix: Line 158 in app.php:  <?php $settings = Cache::getConfig('_cake_core_'); ?>

It shouldn't be reading '_cake_core_' anymore since it has been renamed to '_cake_translations_'.

The line should be:  <?php $settings = Cache::getConfig('_cake_core_'); ?>

**Comment by ADmad** [comment]
Already fixed in #1018
