### ISSUE TITLE
Fix cakephp version on composer.json

### ISSUE THREAD

**Issue by damianoporta** [cakephp/app#218]
Hello,
Please fix cakephp version inside composer.json.
There is not a "cakephp/cakephp": "3.0.*-dev" branch!

**Comment by dereuromark** [comment]
There is not :) But there does not have to be one.

**Comment by damianoporta** [comment]
why do you use it in "require" ?

**Comment by dereuromark** [comment]
You are aware of how composer works? Using tags and alike?
In this case it belongs to the latest 3.0.* tag.

**Comment by ADmad** [comment]
@damianoporta Please read the composer docs for better understanding of how it's versioning works.

**Comment by damianoporta** [comment]
@ADmad Yes I know I am asking why are you using "-dev" why not pointing to the master breanch, It should be stable now, no?

**Comment by josegonzalez** [comment]
It's still in RC, so no, master is not stable.
