### ISSUE TITLE
Inflector rule incorrect in bootstrap

### ISSUE THREAD

**Issue by Jnesselr** [cakephp/app#229]
https://github.com/cakephp/app/blob/master/config/bootstrap.php#L167

That shows that this rule:
Inflector::rules('irregular' => ['red' => 'redlings']);
It seems the correct rule is:
Inflector::rules('irregular', ['red' => 'redlings']);

**Comment by ADmad** [comment]
Yes it's a typo. Do you mind making a pull request fixing it?
