### ISSUE TITLE
ERR_CONNECTION_RESET at Table->get(...)->mapReduce

### ISSUE THREAD

**Issue by Cayan** [cakephp/app#234]
I'm trying to figure out a proper way to handle the new mapReduce instead of the old afterFind, when I tried to call it with the table's get the page just won't load.

It seems like this is a bug, at least the page should be loaded with an error.

Please, let me know if there's a better approach to handle results.
http://pastebin.com/8qP0FMPC

**Comment by Cayan** [comment]
After a lot of documentation reading I understood the concept behind Entity and I got it working.
I'll keep the issue opened since it's about mapReduce.

**Comment by markstory** [comment]
connections being reset has nothing to do with mapReduce() and is more likely to be an issue with timeouts in your database server/php.
