### ISSUE TITLE
Does not print missing view

### ISSUE THREAD

**Issue by Kwaadpepper** [cakephp/app#236]
I just installed cakephp3, done composer install

Now i created a controller accessing to url ```root/controller```.
It should print 'Hey there there is a missing template file "Controller/index.ctp".

Instead i got an Fatal error:
![xdebug](https://cloud.githubusercontent.com/assets/6019313/7247814/d9037ea0-e80d-11e4-86ff-c1b56eb93c92.png)

**Comment by dereuromark** [comment]
What is your code in AppView.php?

**Comment by Kwaadpepper** [comment]
<?php
/**
 * CakePHP(tm) : Rapid Development Framework (http://cakephp.org)
 * Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 *
 * Licensed under The MIT License
 * Redistributions of files must retain the above copyright notice.
 *
 * @copyright Copyright (c) Cake Software Foundation, Inc. (http://cakefoundation.org)
 * @link      http://cakephp.org CakePHP(tm) Project
 * @since     3.0.0
 * @license   http://www.opensource.org/licenses/mit-license.php MIT License
 */
namespace App\View;

use Cake\View\View;

/**
 * App View class
 */
class AppView extends View
{

    /**
     * Initialization hook method.
     *
     * For e.g. use this method to load a helper for all views:
     * `$this->loadHelper('Html');`
     *
     * @return void
     */
    public function initialize()
    {
    }
}

**Comment by Kwaadpepper** [comment]
Ok my bad, i just forgot to change namespace ```App\View``` to ```Hydroclass\View``` in the AppView.php according to my app.php.

So now it prints the error message correctly. Cakephp2 really slowed me down not using modern php ><

Sorry false alert
