### ISSUE TITLE
Exclude 'empty' files in .gitignore

### ISSUE THREAD

**Issue by elboletaire** [cakephp/app#237]
I've tried to add some exclusions to .gitignore so the first time you do a `git add .` the `tmp` and `logs` folder are also added.

I was creating a PR with these changes but I'm not able to add the exclusions for the `tmp` folder. It seems that git ignores its subfolders.

Taking the current `.gitignore` file:

    /vendor/*
    /config/app.php
    /tmp/*
    /logs/*

The `empty` file in the `logs` folder can be excluded like so:

    /vendor/*
    /config/app.php
    /tmp/*
    /logs/*
    !/logs/empty

But with the `tmp` folder, I've tried (without success) all these convinations:

    !/tmp/**/empty
    !/tmp/*/*/empty
    !/**/empty # try to exclude every empty file found (does not work with more than one level)
    !empty

As said, none of them work (at least not in my git environment..).

I think that it would be great to find a way to exclude these files as I'm sure I'm not the only one who needs to manually add these folders after the first clone (because `composer install` crashes when tries to apply its permissions).

If we cannot add the `.gitignore` exclusions maybe the folder creation could be managed by the composer post-install script.

**Comment by markstory** [comment]
Couldn't we explicitly list all the empty files that come with the app skeleton out of the box?

**Comment by bravo-kernel** [comment]
Could somebody please confirm explicitly listing all empty files is the solution so I can create the PR?

**Comment by elboletaire** [comment]
Sorry I lost track of this. Glad to see it has been solved.

**Comment by bravo-kernel** [comment]
Hmmm, just noticed that the explicit exclusions in #238 only work for the ``/logs`` directory and not for ``/tmp`` (most likely caused by the subdirectories as described by @elboletaire).

So far I have had no luck in finding the right syntax.

**Comment by jadb** [comment]
Hm, does that mean we should revert #238?

**Comment by bravo-kernel** [comment]
I remember having to do something similar once and it turns out this was the (only) way to do it:
```
/vendor/*
/config/app.php

/logs/*
!/logs/empty

/tmp/*
!/tmp/cache
/tmp/cache/*

!/tmp/cache/models
/tmp/cache/models/*
!/tmp/cache/models/empty

!/tmp/cache/persistent
/tmp/cache/persistent/*
!/tmp/cache/persistent/empty

!/tmp/cache/views
/tmp/cache/views/*
!/tmp/cache/views/empty

!/tmp/sessions
/tmp/sessions/*
!/tmp/sessions/empty

!/tmp/tests
/tmp/tests/*
!/tmp/tests/empty
```

Tested all situations I could think of using dummy files, then doublechecking ignore behavior by running ``git ls-files --others --exclude-standard`

I have to admit: it does not make the file any leaner

**Comment by ADmad** [comment]
That list looks quite messy. I would revert to just ignoring `/tmp/*` & `/logs/*` as before.

**Comment by ADmad** [comment]
We should have a shell or post install hook to create the directory structure for tmp and logs.

**Comment by bravo-kernel** [comment]
It does look like a mess so :+1: for the post install or shell.

**Comment by elboletaire** [comment]
> We should have a shell or post install hook to create the directory structure for tmp and logs.

:+1:
