### ISSUE TITLE
There is EmailTransport and Email in app.php

### ISSUE THREAD

**Issue by lorenzo** [cakephp/app#253]
One of them need to be removed

**Comment by ADmad** [comment]
So nest transport config under `Email` ?

**Comment by ADmad** [comment]
I like having it separate since config for both is independent of each other.

**Comment by markstory** [comment]
Why does one of them need to be removed?

**Comment by lorenzo** [comment]
Or I may not be understanding what the difference is?

**Comment by markstory** [comment]
Email is for configuring the email object defaults.  While EmailTransport is for configuring SMTP server settings, or mailchimp/mandrill credentials.

**Comment by ADmad** [comment]
I don't think anything needs to be done here, both those configs are needed. :)

**Comment by lorenzo** [comment]
should we add a dock block explaining what they are? It wasn't obvious to me at all

**Comment by markstory** [comment]
I can add something to the docs.

**Comment by ADmad** [comment]
Hmm.. the docblock above these configs does have sections "Configuring transports" and "Configuring delivery profiles". Perhaps the section "Configuring delivery profiles" should be moved directly above the config `Email` ?

**Comment by lorenzo** [comment]
I think that would help

**Comment by markstory** [comment]
Closing as I split the docs up as discussed.
