### ISSUE TITLE
ConsoleShell: adding a -q / --quiet option?

### ISSUE THREAD

**Issue by beporter** [cakephp/app#263]
Doing something like this is currently extremely difficult:

```shell
$ echo 'use Cake\Datasource\ConnectionManager; ConnectionManager::config("default");'
   | bin/cake Console

Welcome to CakePHP v3.0.7 Console
---------------------------------------------------------------
App : src
Path: /var/www/src/
---------------------------------------------------------------
You can exit with `CTRL-C` or `exit`

Psy Shell v0.4.4 (PHP 5.6.10-1+deb.sury.org~precise+1 — cli) by Justin Hileman
=> [
       "className"        => "Cake\\Database\\Connection",
       "driver"           => "Cake\\Database\\Driver\\Mysql",
       "persistent"       => false,
       "host"             => "localhost",
       "username"         => "vagrant",
       "password"         => "vagrant",
       "database"         => "vagrant",
       "encoding"         => "utf8",
       "timezone"         => "UTC",
       "cacheMetadata"    => true,
       "quoteIdentifiers" => false,
       "name"             => "default"
   ]

Exit:  Ctrl+D

```

All of that banner stuff, the `=>` and the `Exit: Ctrl-D` are all seriously in the way if I wanted to consume this output from somewhere else. What I'd really want out of a call like that is this:

```shell
$ echo 'use Cake\Datasource\ConnectionManager; var_export(ConnectionManager::config("default"));'
   | bin/cake Console --quiet
array (
  'className' => 'Cake\\Database\\Connection',
  'driver' => 'Cake\\Database\\Driver\\Mysql',
  'persistent' => false,
  'host' => 'localhost',
  'username' => 'vagrant',
  'password' => 'vagrant',
  'database' => 'vagrant',
  'encoding' => 'utf8',
  'timezone' => 'UTC',
  'cacheMetadata' => true,
  'quoteIdentifiers' => false,
  'name' => 'default',
)
```

Suppressing the banner is easy, but I have not investigated what it might take to suppress Boris's REPL output and **only** print what the provided commands might produce.

I could even see a case being made for `--quiet` being enabled by default when accepting redirected input like this.

**Comment by lorenzo** [comment]
There is already a `-q` and `--quiet` options. What am I missing?

**Comment by beporter** [comment]
```shell
$ echo 'use Cake\Datasource\ConnectionManager; var_export(ConnectionManager::config("default"));' 
   | bin/cake Console -q
Error: Unknown short option `q`
This shell provides a REPL that you can use to interact with your
application in an interactive fashion. You can use it to run adhoc
queries with your models, or experiment and explore the features of
CakePHP and your application.

You will need to have psysh installed for this Shell to work.

Usage:
cake console [-h]

Options:

--help, -h  Display this help.
```

**Comment by beporter** [comment]
TIAS :wink:

**Comment by beporter** [comment]
The issue may be that the ConsoleShell doesn't start with its parent OptionParser like the [ServerShell does](https://github.com/cakephp/cakephp/blob/29ca3d120c25d554ad5143adffdab0f76bc6c9b9/src/Shell/ServerShell.php#L152), for example.

ServerShell:
```php
    public function getOptionParser()
    {
        $parser = parent::getOptionParser();
```

[ConsoleShell](https://github.com/cakephp/app/blob/aaa20c03aa4827d583f54941f57799e4b8d678b1/src/Shell/ConsoleShell.php):
```php
    public function getOptionParser()
    {
        $parser = new ConsoleOptionParser('console', false);
```

I don't think that will be entirely sufficient though to suppress PsyShell's native output.

**Comment by lorenzo** [comment]
Try changing `new ConsoleOptionParser('console', false);` to `new ConsoleOptionParser('console');`

If it works for you, open a PR :D

**Comment by beporter** [comment]
Yep, that get's closer, but as I suspected, it doesn't fully suppress PsyShell's normal interface output:

```shell
$ echo 'use Cake\Datasource\ConnectionManager; var_export(ConnectionManager::config("default")); exit;' | bin/cake Console -q
array (
  'className' => 'Cake\\Database\\Connection',
  'driver' => 'Cake\\Database\\Driver\\Mysql',
  'persistent' => false,
  'host' => 'localhost',
  'username' => 'vagrant',
  'password' => 'vagrant',
  'database' => 'vagrant',
  'encoding' => 'utf8',
  'timezone' => 'UTC',
  'cacheMetadata' => true,
  'quoteIdentifiers' => false,
  'name' => 'default',
)⏎
```

(Note the funky "return" character at the end, even in spite of using an explicit `exit;` in my input string.)

**Comment by beporter** [comment]
So for posterity:

The `⏎` is something PsyShell is adding to `var_export()` specifically. It doesn't get added to `print_r()` or `var_dump()`. Strange. Unfortunately, that character is also getting added to `serialize()`, which is the one that would really help here. To get sane output, I have to do this:

```shell
$ echo 'echo serialize([1, 2, 3]); exit;' | bin/cake console -q | sed s/⏎//
a:3:{i:0;i:1;i:1;i:2;i:2;i:3;}
```

Thanks for the feedback. I think the rest is Psy's problem now.

**Comment by beporter** [comment]
Created bobthecow/psysh#211.

**Comment by ADmad** [comment]
Closing as PR is opened.
