### ISSUE TITLE
4.0 - RFC - A new folder for controllers actions and prefix

### ISSUE THREAD

**Issue by andtxr** [cakephp/app#267]
4.0 - RFC - A new folder for controllers actions?

I was wondering about the possibility of adding a new folder to keep the controller actions templates separated from the others.

Right now the agglomeration of similar named folders prevent some prefix naming. For example:

There will be a restriction if someone has decided to use a route prefix like element, email, or any other name that already exists as default template folder.

Another separation that I think may be interesting is to create a folder for prefixed templates.

Sometimes we have folders named like ``Admin`` for the prefixed templates, and ``Admins`` for the default admins controller actions.

This is someway visually confusing.

What do you think about the following structure for the action templates?

```
app
|____src
     |____Template
          |____Action
```

And this following one for the prefix folders?

```
app
|____src
     |____Template
          |____Action
               |____Prefix
```

I was wondering about it and I would share with you.

I don`t know if it breaks some MVC patterns that you guys had chosen. If it does, sorry.

**Comment by ADmad** [comment]
This issue was moved to cakephp/cakephp#7074
