### ISSUE TITLE
Unify translation strings with placeholder

### ISSUE THREAD

**Issue by dereuromark** [cakephp/app#286]
Currently:

    sprintf(
        __d('cake', 'The requested address %s was not found on this server.'),
        "<strong>'{$url}'</strong>"
    )

but I think we should unify all to the new syntax {0} (which cakephp/cakephp uses throughout):

        __d('cake', 'The requested address {0} was not found on this server.',
        "<strong>'{$url}'</strong>")

Makes it also shorter, no need for sprintf() - but mainly consistent with the rest of the 3.x placeholder translations (no mixin of {0} and %s anymore.

**Comment by HavokInspiration** [comment]
I'm all in favor of consistency.

**Comment by ionas** [comment]
I am all in favour of using descriptive, constant like, strings, instead of English ones. That way in CASE you miss to translate, you see it in your interface very fast. Also aren't there named parameters? Aren't those better almost all time? Especially for translators?

**Comment by dereuromark** [comment]
@ionas I think your request is a RFC of another dimension and totally outside the scope of this issue.

**Comment by ionas** [comment]
Agreed.
Right now I'd though change it to named parameters instead of %s OR {0}. Good?

**Comment by dereuromark** [comment]
PR open.
