### ISSUE TITLE
Suggestion: Default connection

### ISSUE THREAD

**Issue by bobmulder** [cakephp/app#287]
Hey guys,

Some time ago I tried to install Bolt CMS because I heard a friend of mine about it.
The nice thing about it was that there's a default sqlite connection, but of course you can override it to your own mysql/whatever connection.
I liked this idea: let your user start as soon as possible.

My idea is to use a sqlite connection by default. I guess this app template would be the best place to do that?

I would like to hear what you think about it!

Greetz

Bob

**Comment by ionas** [comment]
As DebugKit nowadays requires SQLite as well I am :+1: to have a basic working app + database setup. This could be beneficial to newbies and could also get around migrations for single-developer processes.

**Comment by bobmulder** [comment]
Thats exactly what I mean ;) Yeah!

**Comment by markstory** [comment]
By using SQLite out of the box we're not really setting the user up for 'success' down the road. It is totally easier to get started, but the developer will have to re-do an work they do on SQLite before they can deploy anywhere.

**Comment by bobmulder** [comment]
Hi @markstory, thanks for your feedback.

> ...we're not really setting the user up for 'success' down the road...

I see your your point about this. Of course they need to change to database before deploying. This idea is just created because of quick use. You want to help newbies, or people who just need a fresh cake-app to work on a little (just like me, plenty of times). For deployment you should do configurations, and yes also your database.

**Comment by ionas** [comment]
They could still use migrations and run those against a different sql database, couldn't they? At least as I remember that is how it used to be in rails3.

**Comment by markstory** [comment]
@ionas Sure migrations work. But there are important differences between sqlite and all other databases.

**Comment by ADmad** [comment]
:-1: for the same reason @markstory initially stated.

**Comment by jhli** [comment]
Boils down if you want to endorse a dumb and lightweight default to fokus on the framework like rails does or a more powerful one and derive of/use more features.

**Comment by burzum** [comment]
:-1: I agree with ADmad and Mark.

If people are unwilling or to stupid to read the most basic instructions to set it up defaults won't help them either in the long run. Actually one of the reason I've chosen Cake 1.2 in the past was that it was already pretty easy to set  it up and get started compared to Symfony and Zend at this time!

**Comment by bobmulder** [comment]
:+1: Agree with @burzum
