### ISSUE TITLE
Rename empty placeholder files to .empty

### ISSUE THREAD

**Issue by dereuromark** [cakephp/app#290]
We should rename the placeholder files from a real filename to a dot prepended (hidden) file name such as `.empty` .
This fits to `.gitattributes` and other such meta files we use and have a special semantic use.

**Comment by markstory** [comment]
Ok. Make sure you also update bake, as it removes the 'empty' files when they are no longer needed.

**Comment by ADmad** [comment]
The popularly used name is '.gitkeep'

**Comment by rchavik** [comment]
i would prefer to make it a normal file. easy to see those stray empty files.

**Comment by jadb** [comment]
:+1: for @ADmad's suggestion.

Ref: http://stackoverflow.com/a/7229996

**Comment by ADmad** [comment]
Since we already have those `empty` file I am in favor of just keeping them. It brings no real value renaming them.

**Comment by jadb** [comment]
Agreed, I meant if we are to rename to `.empty`, might as well follow popular convention (which I'd personally prefer). Otherwise, we can stick to what's already there.

**Comment by dereuromark** [comment]
.gitempty is not ideal because other people might be using some other Version control tool.
Anyway closing then for now.
