### ISSUE TITLE
RFC : Adding a `docker-compose.yml`

### ISSUE THREAD

**Issue by cake17** [cakephp/app#293]
More and more people use docker to be able to build an environment identical for dev, test and prod.

I think this could be nice to add a `docker-compose.yml` at the root of the app skeleton. The objective is to be able to build an environment just by typing `docker-compose up -d` that will build all containers and link them together.

We could create official repositories in [Docker Hub](https://hub.docker.com/) with basic cakephp images. At least 2 are needed:
- for `nginx` or `apache` (we could create both)
- for `php-fpm`
- for `mariadb`, `mysql` or `postgres` (not required as official images are enough)

Theses images would rely on the official image of nginx and php. I can create the images under my username to test, and then we could transfer them to cakephp when everything works well. Of course, just if people see an interest on having docker integrated officially.

Any idea on this ?

**Comment by ADmad** [comment]
I would prefer keeping this app skeleton simple, aimed towards newbies and easy to maintain for the team. IMO your suggesting is better suited for say [friendsofcake/app-template](https://github.com/FriendsOfCake/app-template).

**Comment by markstory** [comment]
I like docker, but worry it will open the gates for adding a Vagrantfile, something for otto, phpuphet and so on. Is a dockerfile something we could keep in the docs or even a separate repo?

**Comment by josegonzalez** [comment]
I'd be +1 on both Vagrantfile and dockerfile, and that's it. In fact, I'm pretty sure dockerfile would be fine for people since on OS X it runs via Vagrant.

**Comment by cake17** [comment]
I'm :+1: for creating a `cakephp/docker`repo, something like [this repo](https://github.com/cake17/docker/tree/master/cakephp/3.x).

And we can add a link in the docs to the repo. Or even give more explanation on how to add the docker-compose.yml in a project. (basically the [readme of the repo](https://github.com/cake17/docker/blob/master/cakephp/3.x/README.md))

**Comment by cake17** [comment]
I'm also +1 for having the main images for nginx and php-fpm in dockerhub under the `cakephp` name. (same as [this](https://hub.docker.com/r/cake17/cakephp/tags/))

And a service can be created to automatically create the images on dockerhub when the `cakephp/docker` github repo receives a `git push`.

**Comment by josegonzalez** [comment]
I don't think we need a separate repo for the `docker-compose.yml` file. We could provide an image that gets pulled down. The stuff that creates this image (nginx conf etc.) could be in a separate repo.

**Comment by cake17** [comment]
Just a reminder here: adding cakephp/docs images in dockerhub will help newbies to docker.

Maybe we can have 2 images for cakephp/docs:
- a **light** one : only if you want to build the html
- a **full** one : with all tools needed to build html, pdf, latex, epub ...

**Comment by cake17** [comment]
An app with docker can be found [here](https://github.com/cakephp-fr/app/tree/docker) with instructions. Maybe we can close this.
