### ISSUE TITLE
How to show checkbox checked

### ISSUE THREAD

**Issue by amitgora27** [cakephp/app#305]
in cakephp new version 3.0 which argument we have to show multiple checkboxes checked.

$options = array(1 => 'ONE', 'TWO', 'THREE');
                        $selected = array(1, 3);
                        echo $this->Form->input('interiors', ['multiple' => 'checkbox', 'options' => $options, 'default' => $selected]);

**Comment by dereuromark** [comment]
Default should be correct.
What is the result?

**Comment by amitgora27** [comment]
![cakephp3](https://cloud.githubusercontent.com/assets/7251184/11622921/2fc623f0-9cef-11e5-8720-b6788ca694d5.png)

Please check above screen shot

**Comment by dereuromark** [comment]
Well, your $options aray is invalid, nested arrays do not look like this.
If you debug() it, you will easily figure out why.

**Comment by dereuromark** [comment]
Also please not that this is not a help forum. This is a bug tracker for the application skeleton.

**Comment by amitgora27** [comment]
Thanks for your support and i know man that is not a help forum. But can you give me and tutorial URL where you defined it.

**Comment by jhli** [comment]
Http///book.cakephp.org
IRC, Google Groups

Note: There may be one migration issue; v3 does not pass through sql schema defaults like tinyint(1) default 1 to the orm/formhelper.

For anything else follow dereuromarks recommendation. The options list mist be of correct data/types.

After utilizing book, irc and groups and isolating your case to be a bug (in case it is), THEN an issue should be created on cakephp/cakephp, not cakephp/app.
