### ISSUE TITLE
RFC: Simplifying App base classes

### ISSUE THREAD

**Issue by dereuromark** [cakephp/app#325]
Now, with namespacing, there is no need to have App prefix anymore for any overwriting file in the app.

* AppController => (application) Controller extends CoreController (aliased)
* AppView => (application) View extends CoreView (aliased)
* AppHelper => (application) Helper extends CoreHelper (aliased)

People can add in the same consistent naming pattern other app specific overwrites:

* Entity extends CoreEntity
* Table extends CoreTable
* Shell extends CoreShell

etc
Instead of App* everything this makes it clear what the base class is on project level, and the App word is not reversed anymore. People might have a `apps` table and `AppsTable`/`AppEntity`/`AppsController`, which is perfectly fine.

We might want to do this for 3.3 or 4.0.

Since the aliased usage happens at the first lines of a file it is very clear what you extend:

```php
namespace App\Controller;

use Cake\Controller\Controller as CoreController;

/**
 * Main application Controller
 */
class Controller extends CoreController  {
}
```
and
```php
namespace App\Controller;

/**
 * Fruits Controller
 */
class FruitsController extends Controller  {
}
```

**Comment by josegonzalez** [comment]
Given our history of using "App", this might just confuse users. Hell, I was confused when we didn't have an `AppEntity` class :D

**Comment by dereuromark** [comment]
Maybe people have to get used to namespacing first, so maybe this is sth for 4.0+ at some point to re-discuss.

**Comment by ADmad** [comment]
So instead of 
```
use Cake\Controller\Controller;

class AppController extends Controller
```
you end up with
```
use Cake\Controller\Controller as CoreController;

class Controller extends CoreController  {
```

What benefit does that give?  You never have to instantiate these classes yourself anyway. Having the "App" suffix makes is clearer for new users. I wouldn't get rid of it even in 4.0

**Comment by ionas** [comment]
I suggest adding an example how to extend from another `AppController` e.g. `WebserviceController` or `ApiController` this would include the option to *make space* for the `apps` table use case.

I can see a benefit in adding aliases like, to improve readbility and keep our conventions... 
```php
use Cake\Controller\Controller as CoreController;
class AppController extends CoreController { // ...
```

**Comment by dereuromark** [comment]
@ADmad What benefit does keeping the App thing have? It is mainly there because back in the day it was the only way to make it work. This is now only a soft requirement due to "being used to it". It has no technical benefit.
So thats why it would be good to at least discuss it.

Right now apps have inconsistent overwriting, some use App... some directly the parent class + aliasing.
So this is worse to me.

**Comment by Spriz** [comment]
:+1: from here - doesn't make sense with namespaces, but it's rather "left-over" :smile:

**Comment by lorenzo** [comment]
I'm pretty much against having to alias classes in the `use`, that is partially one of the reasons cake has suffixes for the class names. :-1:

**Comment by davidyell** [comment]
For me the benefits do not outweigh the potential confusion, or the ripple effect of having to update all the docs.

:-1:

**Comment by jippi** [comment]
seems like a :-1: consensus
