### ISSUE TITLE
RFC: Load additional config specified by envvar

### ISSUE THREAD

**Issue by tmatsuo** [cakephp/app#331]
Here is an example implementation.

If an envvar `CAKE_ADDITIONAL_CONFIG` is set, bootstrap.php will load the additional config file.

```php
# after loading the `app.php`
$customConfig = getenv('CAKE_ADDITIONAL_CONFIG');
if ($customConfig !== false) {
    Configure::load($customConfig, 'default', true);
}
```
Potentially it may allow multiple configs with separators, but I think it's too much.

The motivation behind this proposal is to make it easy for us to create a guide for running CakePHP app on [App Engine Managed VMs](https://cloud.google.com/appengine/docs/managed-vms/). Now we're thinking to host this starter app with some modifications (like [this PR](https://github.com/GoogleCloudPlatform/php-docs-samples/pull/23)), but we'd like to directly use cakephp/app if possible.

Thanks

**Comment by josegonzalez** [comment]
What additional config does app engine need?

**Comment by ADmad** [comment]
Why load an additional config file instead of just having an `app.php` as per your needs?

**Comment by tmatsuo** [comment]
> What additional config does app engine need?

Changed needed are:
1. SMTP transport.
1. Session handler
1. Log location (so now we're tweaking `paths.php`)

> Why load an additional config file instead of just having an app.php as per your needs?

Good question. We can provide a whole `app.php` and ask users to replace, but it will override other configs too. With the additional file, we can only provide the necessary bits and I think it's cleaner.

I'm thinking to provide a simple guide like this.

1. Do `composer create_project --prefer-dist cakephp/app bookmarker`
2. download necessary config files and extract in your project dir

This way, we can also say "you can use those files to turn any app Managed VMs ready".

**Comment by josegonzalez** [comment]
Can you paste the contents of that file?

Note there is an upcoming PR that will allow people to configure stuff via env vars, maybe we can piggy-back there: https://github.com/cakephp/app/pull/328

**Comment by tmatsuo** [comment]
> Can you paste the contents of that file?

Sure, here is the diff:
https://github.com/GoogleCloudPlatform/php-docs-samples/commit/4f8fc4308104b96e5a96f4693bd3d37082244c58

And the current app.default.php is here:
https://gist.github.com/tmatsuo/6686c7c0fe5a53737280

As you can see from the diff, we're tweaking paths.php too, for our log collector to pick up the logs. It is great if it's configurable by envvar too.

**Comment by josegonzalez** [comment]
Can you take a look at that pr and let me know what else you'd need, other than the LOGS thing?

**Comment by tmatsuo** [comment]
Oh I noticed that you can change the log file name and also directory by specifying the URL there, which is great :)

I think the only missing thing is the 'ini' configuration for the session handler.

**Comment by josegonzalez** [comment]
@ADmad thoughts on that ini thing? Seems very specific to GoogleCloudPlatform.

**Comment by tmatsuo** [comment]
Right, but the capability of adding configuration is generic thing :)

**Comment by josegonzalez** [comment]
I'm not sold on that particular change. Maybe we can do something like:

```php
'ini' => [
    'session.save_handler' => env('SESSION_INI_SAVE_HANDLER', ini_get('session.save_handler')),
    'session.save_path' => env('SESSION_INI_SAVE_PATH', ini_get('session.save_path')),
]
```

Which is more generic and you can then configure for a specific environment.

**Comment by tmatsuo** [comment]
Ah nice :) I can tweak our docker image to set appropriate SESSION_INI_SAVE_PATH and SESSION_INI_SAVE_HANDLER. Can you add it to your PR?

**Comment by markstory** [comment]
@josegonzalez Would you be able to add the session ini environment variables to your cakephp/app pull request?

**Comment by ADmad** [comment]
Can't you update session ini vars directly in your php.ini?  I am presuming you must be having other customizations in there too.

**Comment by tmatsuo** [comment]
@ADmad Oh good call. It should work. Then #328 will suffice for us. Thanks for your thoughts and great work.

**Comment by josegonzalez** [comment]
I guess no changes to #328 are needed then. I'm closing this :)
