### ISSUE TITLE
Add asset pipeline

### ISSUE THREAD

**Issue by clthck** [cakephp/app#336]
I think asset pipeline feature of Rails is very cool. I will not write about its benefits here as you guys must be familiar with it.
To my knowledge, CakePHP is originally inspired from Rails for its conception.
I know there is a plugin called [AssetCompress](https://github.com/markstory/asset_compress), but looks like it still lacks many features and stability compared to Rails' asset pipeline gem (sprocket-rails).

What I'm going to suggest is as follows:
1) Develop a complete duplicate of sprocket-rails gem (of course it will be CakePHP plugin, probably based on AssetCompress?).
2) Include the newly developed asset pipeline plugin by default just like migrations plugin is included.

**Comment by markstory** [comment]
I'm not sure it makes sense to include an asset pipeline in the default app skeleton. We've been trying to not make the app skeleton a kitchen sink, and instead only include the absolute bare minimum. Bake, and Migrations are plugins that used to be core library features, which is why they are included.

**Comment by dereuromark** [comment]
I would do it the other way around: Develop your own plugin as suggested and use it.
If everything works out and more people start using it there will be the chance to rediscuss.
At this point it is way too theoretical.

**Comment by clthck** [comment]
Asset concatenation and minification plays an important role in performance optimization for production. Don't you think so?

**Comment by clthck** [comment]
And more and more people are using sass. In fact, sass is nearly a default css preprocessor nowadays.

**Comment by markstory** [comment]
> Asset concatenation and minification plays an important role in performance optimization for production. Don't you think so?

I agree. I also know that there are many ways to achieve that goal. PHP based solutions are one option. Many people I talk to end up using tools like grunt, webpack, ember-cli or gulp. Bundling an asset pipeline by default can create additional complex dependencies like node and ruby. While there are PHP implementation of Sass and Less, they often have subtle differences/issues.

**Comment by clthck** [comment]
Looks like it's time to switch to rails.

**Comment by jadb** [comment]
@clthck - unfortunately, not everyone using the app skeleton is building a frontend with it. Lots of us use it for building strictly API backends.

@dereuromark's suggestion of pushing it as a separate plugin would be nice to have (specially if it can compete with what I consider to still be a very solid/elegant solution, AssetCompress).
