### ISSUE TITLE
empty filed allowed to bypass validation rules

### ISSUE THREAD

**Issue by samayo** [cakephp/app#342]
So, I was playing around with cakephp 3's blog tutorial, and at least [this part about adding a method to model](http://book.cakephp.org/3.0/en/tutorials-and-examples/blog/part-two.html#data-validation) to validate empty fields, does not actually forbid me from submitting an article with empty title and body. I just pressed the spacebar a couple of times and the article was submitted. 

Here is the code that is supposed to disallow empty title, body from being submitted. 
I hope I am not missing anything. 
```php 
 public function validationDefault(Validator $validator)
    {
        $validator
            ->notEmpty('title')
            ->requirePresence('title')
            ->notEmpty('body')
            ->requirePresence('body');

        return $validator;
    }
```

**Comment by markstory** [comment]
What does your code do after the validation? Even if validation fails you'll still get a entity out of `newEntity()`.

**Comment by ADmad** [comment]
> I just pressed the spacebar a couple of times and the article was submitted.

A field with whitespace chars doesn't qualify as empty field. If you want to prevent submission of fields with only whitespace chars you need to also add "notBlank" rule.

**Comment by samayo** [comment]
It says, notBlank is deprecated.

**Comment by markstory** [comment]
Where? Both [Validation::notBlank()](http://api.cakephp.org/3.2/class-Cake.Validation.Validation.html#_notBlank) and [Validator::notBlank()](http://api.cakephp.org/3.2/class-Cake.Validation.Validator.html#_notBlank) don't have deprecated markers in the current API docs.

**Comment by markstory** [comment]
I was not able to reproduce this locally using the `notBlank()` validator method. The `notEmpty()` method _will_ treat spaces as 'notEmpty' and must be combine with notBlank() or another validation rule if you want to disallow all whitespace values.
