### ISSUE TITLE
Enhancement: Github Starring Feature on home.ctp

### ISSUE THREAD

**Issue by ionas** [cakephp/app#344]
See https://gist.github.com/ionas/fc52a780844ab3dd309d for the basic idea.
This however needs to go through the server (CORS) and/or requires some GitHub token authentication by the user itself (not just a logged in session).

**Comment by ionas** [comment]
Ref: https://developer.github.com/v3/activity/starring/#star-a-repository

**Comment by chinpei215** [comment]
Interesting.

**Comment by bravo-kernel** [comment]
Just my two cents but I personally think Github stars are dead and should not be introduced. The lack of people actually "liking" is cumbersome (even for great repos) and I think they this give a false impression. Potentially more harmful than helpful.

**Comment by bravo-kernel** [comment]
Unless I totally misread and this is intended to "auto star" the repo.

**Comment by ionas** [comment]
It is not. It would show a star button on the home-page alongside the github icon... and best if you already starred or not (unstarring not possible ... through home.ctp).

The issue with auto-starring is that it is probably against the tos of github as well as not nice towards end users (to quote google before it became: Don't be evil.)

**Comment by ADmad** [comment]
Closing as no one seems interested in pursuing this.
