### ISSUE TITLE
Why doesn't cake use bootstrap by default?

### ISSUE THREAD

**Issue by daveozoalor** [cakephp/app#350]
I was just wondering, what I usually do soon as i am through with cake is switch to bootstrap. 
Why doesn't cake come with bootstrap by default?

**Comment by dereuromark** [comment]
Please always try to look at existing issues first.
Explained @ https://github.com/cakephp/app/pull/142

**Comment by dereuromark** [comment]
As for boostrap, you can use https://github.com/FriendsOfCake/bootstrap-ui/
That involves almost 0 overhead to switch to this (or any other CSS framework).
