### ISSUE TITLE
`composer install` Default Permissions

### ISSUE THREAD

**Issue by ionas** [cakephp/app#353]
When deploying and updating our apps via `composer install` we have run into a few problems regarding permissions.
https://github.com/cakephp/app/blob/master/src/Console/Installer.php#L159

That sets permissions to xx7.
By default however we suggest the permissions to be set to 770 (more secure) or 777 (almost the same like as of now, however if some admin comes along and changes the permissions of the other flag, the cache files will be still readable while xx7 might result into 007).

**Comment by ionas** [comment]
An alternative would be a warning on the console to change this `$worldWritable = 0770;`?
I could setup a PR for that if you think that's sane.

**Comment by ionas** [comment]
Also, what's the benefit of bindec()? instead of a regular *nix bitmask notation?

**Comment by ADmad** [comment]
Not having the files world writable will cause lot of problems to newbies when switching between CLI and webserver. Especially those using packages like WAMP etc.

**Comment by markstory** [comment]
Just change/delete the installer script in your application. The defaults are intended to help new users get going with minimal fuss.

**Comment by ionas** [comment]
@markstory a PR is open. Feel free to close that one if you deem it not any good.
