### ISSUE TITLE
localized Date & Time, Carbon ... formatLocalized()

### ISSUE THREAD

**Issue by arturmamedov** [cakephp/app#362]
Today update CakePHP from 3.1.4 to 3.2.6 and surprise in all application :)!

    Call to undefined method Cake\I18n\Time::formatLocalized() 

I think it's because Time now not extend Carbon? What heppened? What can i do? i need to change all my call to formatLocalized() method with i18nFormat() ?

**Comment by arturmamedov** [comment]
Ok, i return to read the doc, and ...
> Under the hood, CakePHP uses Chronos to power its Time utility. Anything you can do with Chronos and DateTime, you can do with Time and Date.

> Note
> Prior to 3.2.0 CakePHP used Carbon.

For solve now i need to put Carbon back, and do the opposite of Migrating from Carbon described on Chronos page https://github.com/cakephp/chronos

But is a good way? Or its better rewrite my call to Carbon methods with Chronos or Cake Time&Date one?

**Comment by ionas** [comment]
I'd recommend changing the methods. However I am surprised myself, thought Carbon was api-compatible back to the Carbon version where 'we' left off.

**Comment by arturmamedov** [comment]
Sorry i can close this misunderstooded by me issue. 

@ionas its because i use directly the Carbon method formatLocalized()

**Comment by ionas** [comment]
Okay. If you need to localize a whole app you can set stuff like:

```php
        Time::$defaultLocale = 'de-DE';
        Date::$defaultLocale = 'de-DE';
        FrozenTime::$defaultLocale = 'de-DE';
        FrozenDate::$defaultLocale = 'de-DE';
```

And that should do the trick.

**Comment by arturmamedov** [comment]
#### Hi! I get the error again:
```
Error: Call to undefined method Cake\Chronos\Chronos::formatLocalized() 
```
And now i have a `Chronos` object, previously i have `Time`:
```
Time {#339 ▼
  +"time": "2016-03-22T00:00:00+0000"
  +"timezone": "UTC"
  +"fixedNowTime": false
}
```
And by changing from `formatLocalized()` to `i18nFormat()` all work. But with `Chronos` object i don't know what to do. 
From database cake autoconvert to `Chronos` object. I need to reconvert again to `Cake\I18n\Time`?
```
Chronos {#158 ▼
  +"date": "2016-04-30 00:00:00.000000"
  +"timezone_type": 1
  +"timezone": "+00:00"
}
```

I have `cakephp 3.2.11`

**Comment by lorenzo** [comment]
Seems like `formatLocalized()` was intentionally removed in Chronos, but no replacement was left in CakePHP. If you are happy with the output of `i18nFormat()` are you with the other method being removed? I would personally not introduced again as it really was not a good implementation.

**Comment by arturmamedov** [comment]
Understood. So i can't get localized format from Chronos object. And i need to convert to Chronos to time, right? 
Its very unusefull :( because we get a Chronos object in Entities and need to work with it.

**Comment by arturmamedov** [comment]
### My mistake: i have `DateFrozen` object and `DateTimeFrozen`  from database and this make sense.
I can use the `i18nFormat()` [with the formats ](http://www.icu-project.org/apiref/icu4c/classSimpleDateFormat.html#details
)and enjoy my localized App: 
```
I18n::locale('it_IT');
// output:  28 mar 2016 
<?php echo $offer->date_from->i18nFormat('d MMM Y'); ?> 
```
## CakePHP Documentation: http://book.cakephp.org/3.0/en/core-libraries/time.html#formatting
