### ISSUE TITLE
Easier integration with Let's Encrypt

### ISSUE THREAD

**Issue by markstory** [cakephp/app#368]
_From @watermark on April 13, 2016 17:6_

This is a (multiple allowed):
- [ ] bug
- [x] enhancement
- [ ] feature-discussion (RFC)
- CakePHP Version: Any
- Platform and Target: Apache
### Summary

Let's Encrypt is out of beta now.  I think we can all agree that more HTTPS is a good thing.  I'd like to suggest a modification to CakePHP to better support Let's Encrypt.
### Issue

The automated verification that the letsencrypt client does places a file at "/.well-known/acme-challange/filename", where filename is a name set by the letsencrypt verification process.  CakePHP redirects all requests to the webroot directory, which can interfere with this process.

Technically, it is possible to setup the let's encrypt client to place the challenge file structure in the webroot directory; however, many of the automated utilities that are coming out don't expose this setting.  You might argue that it's a failing of those utilities, but it's also an easy fix in CakePHP.
### Recommendation

Add lines to the top of the default htaccess such that it passes the request on to Apache, bypassing cakephp.

Add "RewriteRule ^(\.well-known/.*)$ $1 [L]" as the first rewrite rule in the root htaccess and the app/.htaccess
### The .well-known directory

The ".well-known" directory is defined in RFC 5785.  Given my understanding of the RFC, I believe it's appropriate to expose the entire directory as suggested above.

_Copied from original issue: cakephp/cakephp#8642_

**Comment by markstory** [comment]
Seems reasonable to me. Could you send a pull request to cakephp/app with the requested changes?

**Comment by ravage84** [comment]
Can we make this rewrite rule to be commented out by default?
The less rules, the faster the processing.

But :+1: for making the Let's Encrypt integration easier, nontheless.
Exposing the whole ``.well-known`` directory seems to be :ok: .

Also, we should back-port this to 2.x as it non-obtrusive, escpecially when commented out.

**Comment by BassemN** [comment]
@watermark :+1: @ravage84 :+1:

**Comment by watermark** [comment]
I'm for making it the default, not commented out by default.

I'd argue that the one extra rule will have a near zero impact on performance.  Especially because Cake is already using an htaccess and enables mod_rewrite.  I cannot find any performance numbers to support either argument.

Just as you're free to remove the htaccess and enable "CakePHP pretty URLs", you would be free to remove this new addition as well.

**Comment by ravage84** [comment]
Created a PR for 2.x
https://github.com/cakephp/cakephp/pull/8647

**Comment by ADmad** [comment]
Closing as related PR has been merged.
