### ISSUE TITLE
CakePHP installation issue with PHP 5.6

### ISSUE THREAD

**Issue by koffisani** [cakephp/app#370]
I installed Cake with PHP 5.6 : 

`composer create-project --prefer-dist cakephp/app my-cakeapp`

Trying to access my app, I get an exception : 

`Fatal error: Class 'DateTimeImmutable' not found in /opt/lampp/htdocs/my-cakeapp/vendor/cakephp/chronos/src/Chronos.php on line 50`

What can I do to fix this ? Please, help me.

**Comment by ADmad** [comment]
Did `composer create-project --prefer-dist cakephp/app my-cakeapp` complete without errors?

Are you sure you have PHP 5.6? `DateTimeImmutable` in included in PHP itself for 5.5+.

**Comment by ADmad** [comment]
Also I would suggest using the LAMP packages provided by your linux distro instead of using XAMPP. Based on the support questions I have seen the latter is a pain to configure properly.

**Comment by ionas** [comment]
If you want to separate your host from your guest (or use windows for development...) maybe consider using something like:
* https://gist.github.com/ionas/d45e44b9576fdc9f2f02c3c25dfa3501
* https://github.com/alt3/cakebox
* https://github.com/FriendsOfCake/vagrant-ansible
* https://github.com/gourmet/platform
* https://github.com/cpierce/cakephp-vagrant-setup

**Comment by markstory** [comment]
You need to use PHP 5.6 in the webserver as well as on the CLI.

**Comment by ionas** [comment]
Didn't we change the bootstrap.php to test PHP > 5.5.9 in bootstrap?
https://github.com/cakephp/app/blob/master/config/bootstrap.php#L36-L39
E.g. wouldn't / shouldn't an error show up before `Fatal error: Class 'DateTimeImmutable' not found in /opt/lampp/htdocs/my-cakeapp/vendor/cakephp/chronos/src/Chronos.php on line 50` then, already?

**Comment by koffisani** [comment]
Changed LAMPP version, as updating PHP doesn't take effect in LAMPP.

**Comment by ApoorvaJu08** [comment]
how to update lampp

**Comment by dakota** [comment]
@ApoorvaJu08 You will need to ask the Lampp developers that question. We can't help with that.

**Comment by ApoorvaJu08** [comment]
okay
