### ISSUE TITLE
Move all "bootstrapping" code to bootstrap.php

### ISSUE THREAD

**Issue by ionas** [cakephp/app#371]
Could we move all this code:
https://github.com/cakephp/app/blob/master/webroot/index.php#L17-L26
and this code:
https://github.com/cakephp/app/blob/master/webroot/index.php#L28-L37

... to bootstrap.php?
This would mean:
- built-in webserver detection is happening at the start of bootstrapping (and should/can be outcommented on most installations)
- the dispatcher is happening at the end of bootstrapping (and could be swapped/changed etc)

**Comment by markstory** [comment]
> the dispatcher is happening at the end of bootstrapping (and could be swapped/changed etc)

Why can't it be swapped where it is?

**Comment by ionas** [comment]
The reason is basically that you would have control about the whole bootstrapping process within well.. bootstrap.php (or bootstrap.php loading dispatch.php or whatever at the bottom).

The index.php file would only be the entry point for the webserver and nothing else.

**Comment by ionas** [comment]
It also means that if you upgrade cakephp you have one file less to worry about diffing/merging.

**Comment by ionas** [comment]
This was the issue that made me think that index.php should be dumb and bootstrap.php should do some checks at the top before anything else happens:
https://github.com/cakephp/app/issues/370#issue-150561982

**Comment by ionas** [comment]
Shouldn't
```
// for built-in server
if (php_sapi_name() === 'cli-server') {
    $_SERVER['PHP_SELF'] = '/' . basename(__FILE__);
    $url = parse_url(urldecode($_SERVER['REQUEST_URI']));
    $file = __DIR__ . $url['path'];
    if (strpos($url['path'], '..') === false && strpos($url['path'], '.') !== false && is_file($file)) {
        return false;
    }
}
```
... now be in the middleware as one item (that can simply be disabled in Application.php)?

**Comment by markstory** [comment]
I'm not sure it can entirely be middleware as it has to muck with the `$_SERVER` vars. I can look into whether or not the PSR7 lib we're using removes the need to include this though.

**Comment by markstory** [comment]
Closing as I think this is 'done'. At the very least it is doable in applications where people want it to be done.

**Comment by ionas** [comment]
What about: https://github.com/cakephp/app/blob/3.next/webroot/index.php#L17-L26
```php
// for built-in server
if (php_sapi_name() === 'cli-server') {
    $_SERVER['PHP_SELF'] = '/' . basename(__FILE__);
    $url = parse_url(urldecode($_SERVER['REQUEST_URI']));
    $file = __DIR__ . $url['path'];
    if (strpos($url['path'], '..') === false && strpos($url['path'], '.') !== false && is_file($file)) {
        return false;
    }
}
```
- Can't this be moved to some Middleware that can be enabled/disabled.
- If not, can it be moved to bootstrap?

**Comment by markstory** [comment]
> Can't this be moved to some Middleware that can be enabled/disabled.

Could but why?. Its only useful in the cli-server context, and having a middleware would mean it would be run on every request.
