### ISSUE TITLE
Move environment checks to the top of boostrap.php

### ISSUE THREAD

**Issue by ionas** [cakephp/app#372]
Could we move https://github.com/cakephp/app/blob/master/config/bootstrap.php#L36-L49 to the top of the file?

**Comment by markstory** [comment]
Yes. We have the technology to cut and paste code around :smile:

**Comment by ionas** [comment]
:+1: for humor. I ll do it via GH.

**Comment by markstory** [comment]
Thanks :+1:

**Comment by ionas** [comment]
PR https://github.com/cakephp/app/pull/373
