### ISSUE TITLE
`config/app.php` missing after `git clone` and `composer install`

### ISSUE THREAD

**Issue by fquffio** [cakephp/app#381]
What I did:
```
$ git clone https://github.com/cakephp/app.git
Cloning into 'app'...
remote: Counting objects: 10294, done.
remote: Compressing objects: 100% (18/18), done.
remote: Total 10294 (delta 7), reused 0 (delta 0), pack-reused 10273
Receiving objects: 100% (10294/10294), 2.07 MiB | 1.94 MiB/s, done.
Resolving deltas: 100% (4488/4488), done.
Checking connectivity... done.

$ cd app/

$ composer install --ignore-platform-reqs
You are running composer with xdebug enabled. This has a major impact on runtime performance. See https://getcomposer.org/xdebug
Loading composer repositories with package information
Updating dependencies (including require-dev)
    Prefetch start: total: 23
    Finished: success:0, skipped:23, failure:0, total: 23
  - Installing aura/installer-default (1.0.0)
    Loading from cache

  - (...omitted for brevity...)

  - Installing cakephp/bake (1.2.3)
    Loading from cache

symfony/console suggests installing symfony/event-dispatcher ()
symfony/console suggests installing symfony/process ()
symfony/var-dumper suggests installing ext-symfony_debug ()
psy/psysh suggests installing ext-pcntl (Enabling the PCNTL extension makes PsySH a lot happier :))
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
cakephp/debug_kit suggests installing ext-sqlite (DebugKit needs to store panel data in a database. SQLite is simple and easy to use.)
Writing lock file
Generating autoload files
> Cake\Composer\Installer\PluginInstaller::postAutoloadDump

$ ls config/
app.default.php		bootstrap_cli.php	routes.php
bootstrap.php		paths.php		schema
```

According to [Composer docs](https://getcomposer.org/doc/articles/scripts.md#command-events), this is due to `post-install-cmd` being executed only when a `composer.lock` file is present. To solve this, a `post-update-cmd` should be added as well as a `post-create-project-cmd` was added after #355.

Even though you encourage to use `composer create-project`, there are some cases in which a `composer install` from scratch could be useful (CI, for instance), and I would find handy to have the post-install commands run by default in those scenarios, too.

If you agree, I might submit a pull-request.

**Comment by ADmad** [comment]
The app skeleton is only meant to be used as starting point as hence using `composer create-project` is the appropriate command to use. You should then create your own git repo for your app.

**Comment by fquffio** [comment]
@ADmad Yeah, sure. Hence this is a starting point, though, I just thought it could have been useful to other people to have this problem solved already in the `composer.json` as they fork this repo or "`composer create-project`" it.

**Comment by markstory** [comment]
Wouldn't `post-update-cmd` run after each `composer update` as well?

**Comment by ADmad** [comment]
It would and that's not what we want.

**Comment by fquffio** [comment]
Why not? If the `config/app.php` is already in place with a custom security salt, that command basically does nothing.

I'm sorry, but I am missing the point of having a `post-install-cmd`. If the only purpose of that hook is to help getting started with the project when running `composer create-project` and never again, then the `post-update-cmd` should be as undesired as the `post-install-cmd`, right? Instead, I personally found very useful that `post-install-cmd` as it allows the wizard to be run even for cloned projects that aren't registered on Packagist (yet) as long as the `composer.lock` is versioned, and I wish that the same happened if no `composer.lock` was there yet.

Anyway, never mind: I did this in my project and I thought it would have been useful to others too. I must have been mistaken. 😉

**Comment by luke83** [comment]
i agree with @fquffio and @markstory
