### ISSUE TITLE
Session table to use char(40) instead of varchar(40)

### ISSUE THREAD

**Issue by thinkingmedia** [cakephp/app#383]
I think the `sessions.sql` file has been around for several years now, but today I noticed that it was using `varchar(40)` as the primary key.

MySQL (not sure about other DBs) will allow you to use `varchar` as a primary key column, but there are a number of references that say performance can be poor. This of course is relative to the number of rows in the table.

Still, I think this should be changed to just `char(40)` since this column holds the hash key for the session ID and it's length doesn't vary.

Can anyone think of a reason why this would break anything by changing it?

**Comment by markstory** [comment]
It shouldn't break anything, as the column was a max of 40 chars before, and will be that now as well.

**Comment by thinkingmedia** [comment]
I've started using `char(40)` and no issues so far.

**Comment by markstory** [comment]
Closing as a pull request is open now.
