### ISSUE TITLE
Installation Weirdness

### ISSUE THREAD

**Issue by tedewen** [cakephp/app#385]
I started with the quickstart http://book.cakephp.org/3.0/en/tutorials-and-examples/bookmarks/intro.html

I realised something was wrong when there was no app.php. I copied the example over and edited to connect the db. Went to the app root and got all checkmarks.

Went to bake the first scaffoldings. A lot of html, css, and js appeared in the terminal, but there were no files generated. /bookmarks reported that there was no controller class. Checked the 

Did some searching and found that there might be a disconnect between the served php version and the shell php version. In my case 7.0 was being served, but 4.2 was used by the shell. I corrected this in my .bashrc  but the bakes still failed - loads of scrolling code - but no files.

Went into irc for help.

Removed project folder, reinstalled project and all went well. I got the prompt asking about folder permissions and different styling on the index.

**Comment by AD7six** [comment]
Is this a bug report? I don't see anything actionable here.

Showing what you did, and what happened, would be a lot more useful than a narrative.

**Comment by ADmad** [comment]
> Removed project folder, reinstalled project and all went well.

Since the end result is all good, whatever mistake you made earlier seems to be sorted out with help from IRC. So there's nothing to be done here.

**Comment by ionas** [comment]
It took probably 30 minutes to figure out the issue for @hmic and me.
The host was a shared host with crappy environments.

# Suggestion
If we can, try to tell the user that his environment does not match.

# Issue
```json
    "require": {
        "php": ">=5.5.9",
```
In composer.json seems not to have worked with PHP 4.2 CLI.

> Is this a bug report? I don't see anything actionable here.
The action would be to at least make sure a minimal PHP version is running. Somehow that failed. Also what @tedewen forgot to mention is that somehow on PHP 4.2 CLI for him he got an old cakephp version (3.0.x or 3.1.x) - I admit this might be more a composer issue but we should be aware that given ancient PHP versions our installation procedures fail without telling exactly why.

**Comment by ADmad** [comment]
Composer's [requirements](https://github.com/composer/composer#requirements) states it needs PHP 5.3.2 or above. So composer itself should have not run or shown some error message when trying to run it on PHP 4.2. If it didn't that's something that should be reported to composer.

**Comment by ionas** [comment]
@tedewen So in case you care please open up a ticket here https://github.com/composer/composer but be a bit more specific and provide details of each step of what you did and what failed. I ll be quite now (I just don't want us to repeat helping with the same issues).
