### ISSUE TITLE
How to use .env configurations

### ISSUE THREAD

**Issue by arturmamedov** [cakephp/app#391]
Sorry guys, but i don't unserstand how to use the ```.env('key', default)``` configuration. 
Can someone provide me a link to a good tutorial or documentation part(but i search in documentation without good result).

Thanks in advance and happy coding!

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by bravo-kernel** [comment]
Since it was not (instantly) obvious by reading the configuration chapter I will update the docs to make more clear that:

1. user needs to create a `config/.env` file
2. should fill it desired settings as described in the book and example below
3. cake will automatically prefer a setting exposed via `.env` over its peer setting in `app.php`

```env
# ------------------------------------------------------------------------
# Create localized configuration file `/config/.env` using this template.
# ------------------------------------------------------------------------

export DEBUG=true

# general application configuration
export APP_NAME=api.local
export APP_ENCODING=UTF-8
export APP_DEFAULT_LOCALE=en_US

# security settings
export SECURITY_SALT="test-salt"

etc.
```

**Comment by arturmamedov** [comment]
@bravo-kernel Thank you very much!!! .env are very usefull! 

@ADmad thank you to, i keep it in mind next time :+1:
