### ISSUE TITLE
Undefined method Cake\I18n\Time::setDefaultOutputTimezone()

### ISSUE THREAD

**Issue by BassemN** [cakephp/app#392]
Hi,
I'm using the latest `master` branch. After updating composer, I got this fetal error
`Fatal error: Call to undefined method Cake\I18n\Time::setDefaultOutputTimezone() in C:\wamp\www\my-project\config\bootstrap.php on line 110`

**Comment by ADmad** [comment]
If you use master branch of app skeleton you need to use the master branch of cakephp core too. Rather it's better if you use the latest release of app skeleton instead of master.

**Comment by BassemN** [comment]
Thank you @ADmad
