### ISSUE TITLE
Installer::postInstall and config/paths.php

### ISSUE THREAD

**Issue by kminek** [cakephp/app#402]
hi,

it would be nice to respect path constants defined in `paths.php` by `Installer::postInstall` as user could define custom TMP and LOG location for instance: `/app/storage/logs` or `/app/storage/tmp`

**Comment by markstory** [comment]
You can always update/replace the code in the `postInstall` to do exactly what you need :smile: But using the default constants should be doable.

**Comment by ADmad** [comment]
Closing as no one seems interested in making a PR for suggested changes.
