### ISSUE TITLE
Convenience: error.ctp should simply require default.ctp

### ISSUE THREAD

**Issue by htstudios** [cakephp/app#409]
This makes sure you don't accidentally forget about copying changes you do to default.ctp to your error.ctp. E.g. not testing failing http-auth for instances which will then still display "CakePHP: the rapid development php framework" instead of your application 'stuff'.

**Comment by htstudios** [comment]
If you agree I can do the PR

**Comment by markstory** [comment]
We used to have that, and had to deal with numerous issues around people not being able to show error pages as their default layout made a bunch of assumptions about application state that simply didn't exist in an error page context.

It sounds like folks need to do some testing with debug=0 before going live.

**Comment by htstudios** [comment]
Did we have it implicitly or explicitly? Like did it load the same layout (default) by default or did we have require within `error.ctp`?

I do totally see the bout about the assumptions and things. 
I still think a require is pretty transparent if it was implicitly loading default.ctp before (just if).

As an alternative we could create an error layout that has no branding. I could do a PR for that. In case someone forgets it doesn't show "CakePHP" error pages?

**Comment by markstory** [comment]
> As an alternative we could create an error layout that has no branding. I could do a PR for that. In case someone forgets it doesn't show "CakePHP" error pages?

Making the default error layout branding free sounds like a reasonable solution to me. It'll mean less HTML that developers need to remove as well.
