### ISSUE TITLE
Composer update jumping to CakePHP 3.3

### ISSUE THREAD

**Issue by BassemN** [cakephp/app#415]
Hi,

My CakePHP App Skeleton is based on version 3.2.6.
When I run `composer update`, it is updating CakePHP (3.2.13) to (3.3.0). I think it should update to 3.2.14 instead of jumping to 3.3 as I'm on 3.2 branch.

Thanks

**Comment by dereuromark** [comment]
No, that's because 3.3 is supposed to be BC to 3.2.
If you want to keep 3.2.* only, make sure you adjust your composer.json accordingly.

**Comment by BassemN** [comment]
Thank you, I'll upgrade.
