### ISSUE TITLE
Conflict with logs directory

### ISSUE THREAD

**Issue by BassemN** [cakephp/app#424]
Hi,
Some web hosts have logs directory into their web roots and this causes a conflict with the cake one.
Please advise

**Comment by dereuromark** [comment]
If you set it up correctly, the logs file is not part of the webroot, its below the surface.
You should have /webroot as web root.

**Comment by ADmad** [comment]
Also the logs folder is configurable. You can change the `LOGS` constant in `config/paths.php` and/or [Log](https://github.com/cakephp/app/blob/master/config/app.default.php#L288) config in `app.php`.

**Comment by BassemN** [comment]
Thanks @dereuromark @ADmad
