### ISSUE TITLE
RFC CakePHP 4.0.0: Remove all inline javascript @ cakephp/app + cakephp/bake

### ISSUE THREAD

**Issue by inoas** [cakephp/app#426]
# Suggestion

Remove all inline Javascript when CakePHP 4.0.0 ships:

1. Default Flash Helpers hiding
2. Delete Button confirmation
3. (Is there any further inline javascript?)

Any javascript remaining should be as minimalist as possible, unobtrusive, possibly in cake.js, so should be any hooks, such as class attributes.

Ref: https://github.com/cakephp/app/pull/425#issuecomment-242894856

**Comment by ADmad** [comment]
Delete button confirmation should be kept.

**Comment by inoas** [comment]
Okay then I am going to close this. I would only invest to make things consistently clean.

**Comment by inoas** [comment]
No jQuery. Just very basic vanilla js. It would do nothing else the inline scripts do + some getByElementId or getByClassName and for loops.

Paginator rendering inline javascript is the worst so far. But nvm.

**Comment by markstory** [comment]
Can 'vanilla' js do what we need without bumping into a variety of DOM issues and cross browser compatibility issues?

PaginatorHelper's inline javascript can be 'fixed' by updating templates.

**Comment by dereuromark** [comment]
Refs https://github.com/cakephp/cakephp/issues/7511

**Comment by inoas** [comment]
@markstory I suggest all we do is copying the code we currently run for

- delete confirm dialogs
- default flash element templates
- paginator disabled buttons (however this can be possibly done through <a href=""><button></a> and setting that to disabled)

Put that code within `getElementByClassName` + `for` at the bottom of the DOM/page (thus it is "ready")
