### ISSUE TITLE
PaginatorHelper sort() method generates links without keeping the GET parameter: limit

### ISSUE THREAD

**Issue by KostasDaskal** [cakephp/app#430]
My url is: 
`/users?advanced_search=1&username=Greg&limit=100`

I use the paginator helper to generate sort urls like so: 
`$headers[] = $this->Paginator->sort('username', 'Name');`

The resulting Url to click on for sorting at my table header is: `users?advanced_search=1&usrname=Greg&sort=usrname&direction=asc`

The limit parameter is gone, resulting to a default 25 users that I set if no limit is found instead of 100.

Diving into the framework, the magic happens at PaginatorHelper::generateUrl method:

```
$paging = $this->params($model);

$paging += ['page' => null, 'sort' => null, 'direction' => null, 'limit' => null];
$url = [
   'page' => $paging['page'],
   'limit' => $paging['limit'],
   'sort' => $paging['sort'],
   'direction' => $paging['direction'],
];
```

`$paging['limit']` is always null, this is the result of `debug($paging)`:

```
[
    'finder' => 'all',
	'page' => (int) 1,
	'current' => (int) 2,
	'count' => (int) 2,
	'perPage' => (int) 100,
	'prevPage' => false,
	'nextPage' => false,
	'pageCount' => (int) 1,
	'sort' => null,
	'direction' => false,
	'limit' => null,
	'sortDefault' => false,
	'directionDefault' => false
]
```

From what I understand, limit will always be overwritten to null no matter what limit I set or pass, unless I do something hacky in the framework like:
```
$url = [
            'page' => $paging['page'],
            'limit' => $this->request['query'] ? $this->request['query'] : $paging['limit'],
            'sort' => $paging['sort'],
            'direction' => $paging['direction'],
        ];
```

Does limit live on as the "perPage" parameter?
this is what the function generateUrl returns at the end:
`/2.0/users?advanced_search=1&amp;usrname=Greg&amp;sort=usrgroup&amp;direction=asc`
Cakephp version is 3.2.3

**Comment by dereuromark** [comment]
This is the wrong repository. https://github.com/cakephp/cakephp/issues is the bug tracker.

**Comment by KostasDaskal** [comment]
My bad
