### ISSUE TITLE
We need a .github contributor file

### ISSUE THREAD

**Issue by dereuromark** [cakephp/app#431]
We need a file for PR templates here ( see https://github.com/cakephp/app/issues/430 )
that explains:

```
Note: This is only a bugtracker for app skeleton issues.
For CakePHP core framework issues please see https://github.com/cakephp/cakephp/issues bugtracker.
```

or alike

**Comment by ravage84** [comment]
You mean a Contribution guide?

**Comment by dereuromark** [comment]
No a PR autofill file

**Comment by ravage84** [comment]
Ah, I see, you mean a PR and/or issue template like

https://github.com/cakephp/cakephp/blob/master/.github/PULL_REQUEST_TEMPLATE.md
https://github.com/cakephp/cakephp/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by dereuromark** [comment]
Sounds like I mixed
