### ISSUE TITLE
Layout issues for default template

### ISSUE THREAD

**Issue by dereuromark** [cakephp/app#437]
When working with a default template I noticed a few quite inconvenient things I did not know from bootstrap layouts so far.
Not sure if they are specific to foundation or how easy they can be fixed, but if possible they should.
The default layout should be working a bit more solid.

E.g.
- [ ] All index pagination pages are displaying the content very badly by default. they overlap in a way that the content becomes unreadable - with only a few fields already.
Instead they should just get a bit wider and not have the content flow into the next column.
- [x] The pagination should by default always include first() and last(), or navigating through more than a few hundred records is very annoying, it is easy to add IMO.
- [x] The default text only displays pages now, it should however include the record count as well as it used to before, otherwise it is not possible to easily know how many records there are.

**Comment by inoas** [comment]
> All index pagination pages are displaying the content very badly by default. they overlap in a way that the content becomes unreadable - with only a few fields already. Instead they should just get a bit wider and not have the content flow into the next column.

The table content is a hard problem to tackle.
I did solve it through responsive tables but the PR was rejected.
Some ideas, untested:

```css
.index th, .index td {
min-width: 3em;
word-break: break-all;
hyphens: auto;
padding: .1em;
text-align: left;
vertical-align: top;
line-height: 120%;
}
```

That should still look "okay" and at the same time allow a lot of columns to be displayed - horizontally.

As for the other points 👍

**Comment by markstory** [comment]
>  Instead they should just get a bit wider and not have the content flow into the next column.

That is a non-trivial problem to solve.

**Comment by dereuromark** [comment]
I remember with bootstrapv3 templates that they just get "widened" and maybe it overflows on the right side, but that is to be preferred over unreadable content IMO.

**Comment by joshwyrick** [comment]
I have added a `max-width`, and ` text-overflow: ellipsis;` with `overflow: hidden;` to table cells when scaffolding, to help with table display. Maybe something along those lines would work?

Example:

    `td {
	    min-width: 25px;
	    max-width: 150px;
	    text-overflow: ellipsis;
	    overflow: hidden;
    }`

**Comment by inoas** [comment]
I don't like overflow: hidden over word-break: break-all.

**Comment by dereuromark** [comment]
Yes, adding `word-break: break-all;` makes it work out of the box it seems.
