### ISSUE TITLE
IDs for base layout too generic

### ISSUE THREAD

**Issue by dereuromark** [cakephp/app#440]
I knew this was gonna haunt us some day.

When trying to bake some table with a "content" textarea field it gets a "width: 95" because `#content` apparently is used then for both base layout container and the textarea field itself.

So either we 
- reapply model prefixing for form fields (which I was always a big fan off to avoid those clashes in the first place)
- or we are less generic with the default classes and ids used in the main layout, e.g. `layout-` prefix: `#layout-content: {...}`

Our base template shipped with the app should be usable without lots of clashes, it should have good and sane default values to work with out of the box.

**Comment by dereuromark** [comment]
Actually I don't see any usage of that id in the template right now.
Is that maybe a relict we can remove?
```
#content {
  margin:0 auto;
  padding-top:2em;
  width:95%;
}
```

**Comment by inoas** [comment]
Just use `<main>` instead.

**Comment by ADmad** [comment]
I don't think `<main>`  is constantly supported by browsers yet. Definitely not by IE.

IDs shouldn't be used for CSS anyway. Just switch to class and remove the ID.

**Comment by dereuromark** [comment]
The error templates seem to be the only ones not fixed up to use classes yet. Reopening for now.
