### ISSUE TITLE
Set productive setting as default always

### ISSUE THREAD

**Issue by dereuromark** [cakephp/app#442]
According to https://github.com/cakephp/app/blob/master/config/bootstrap.php#L96-L99
The productive cache lengths are set if !debug:

``` php
if (!Configure::read('debug')) {
    Configure::write('Cache._cake_model_.duration', '+1 years');
    Configure::write('Cache._cake_core_.duration', '+1 years');
}
```

But in in fact, similar to debug mode, it should always be set by default to production system and then optionally modified for local dev:

``` php
// Set production defaults in app.php to very long time (+1 year)

if (Configure::read('debug')) {
    Configure::write('Cache._cake_model_.duration', '+10 seconds');
    Configure::write('Cache._cake_core_.duration', '+10 seconds');
}
```

etc.

**Comment by markstory** [comment]
Ok.

**Comment by lorenzo** [comment]
Sounds like a good idea to me

**Comment by ADmad** [comment]
@dereuromark Would you like to make a PR so that this issue can be closed?

**Comment by dereuromark** [comment]
I'd appreciate it if someone had the time to make the PR.

**Comment by dereuromark** [comment]
PR open.
