### ISSUE TITLE
RFC - Add SecurityComponent by default 

### ISSUE THREAD

**Issue by steinkel** [cakephp/app#444]
suggested by Tim Summers

This is a (multiple allowed):
- [ ] bug
- [ ] enhancement
- [x] feature-discussion (RFC)
### Expected Behavior

SecurityComponent added to the application skeleton by default

In our latest CakePHP 3 training session, one of the attendees (Tim Summers) suggested this change to the app skeleton, and I think this could be a good idea to ensure people starting with the framework who didn't ever noticed the SecurityComponent exists would use it by default. It could be removed later on if needed.

What do you think?

**Comment by markstory** [comment]
My biggest concern with enabling SecurityComponent by default is that it makes building forms that use Javascript harder to work with. Enabling `CsrfComponent` by default has similar challenges around AJAX forms.

**Comment by dereuromark** [comment]
I am 👎 here, it should be enough to point out things in the docs.
But most apps might also be backend apps and there it is also often times counter-productive to enable this by default.

**Comment by thinkingmedia** [comment]
We could add the component and then comment it out with a message explaining when you should use it?

I think @steinkel wants to promote it's usage for those who *should* be using it, but are not. It's not about forcing it upon users.

**Comment by dereuromark** [comment]
Commenting out could be a compromise.

**Comment by steinkel** [comment]
Closed per #446
