### ISSUE TITLE
Why RequestHandler component loaded by default?

### ISSUE THREAD

**Issue by BassemN** [cakephp/app#447]
Hi,
Why the app is loading RequestHandler component by default as you can see [here](https://github.com/cakephp/app/blob/8dd9dce39feef06209c9d3d06d3c52f075853c4c/src/Controller/AppController.php#L44)? I don't see it is used in anywhere on the app
Thanks

**Comment by thinkingmedia** [comment]
It's the most commonly used component.

**Comment by dereuromark** [comment]
If you don't want/need it just remove it again in your own app clone.
