### ISSUE TITLE
Defaulting _serialize to true

### ISSUE THREAD

**Issue by watermark** [cakephp/app#448]
Related to #244 and #246.  I'd like to discuss rolling these updates back.

IMO, this code unnecessarily breaks backwards compatibility with Cake2 and causes inconsistency within the framework.  I'm aware this is just the default app, so we're welcome to remove it as needed, but there is no mention of it in the documentation, which caused a decent amount of troubleshooting to track down.  That section of code effectively defaults serializing to true for json and XML only. 

This default forces you to explicitly set '_serialize' to false when rendering an xml or json view in order to disable serialization.  Serialization defaults to false in Cake2, so this breaks some backwards compatibility.  I don't understand the benefit in doing this, so I believe this is done unnecessarily.

The documentation only mentions needing to explicitly set '_serialize' to true in order to enable it, it doesn't mention needing to explicitly setting it to false in certain circumstances.  Given that this is the recommended/default app template, I believe it should at least me mentioned.

This is also a conditional default (as it only applies to XML and JSON), which creates inconsistency within the framework.  It doesn't apply to all extensions.  This inconsistency adds unnecessary confusion.

**Comment by ADmad** [comment]
Compatibility with cake2 is irrelevant this late in cake 3's release cycle, nor are backwards compatibility guarantees made between major versions anyway. Serialization is done by default only for xml and json hose are the only two for which serialization makes sense and the core has specific view classes for.

**Comment by watermark** [comment]
Then I suppose my only remaining point is that the documentation doesn't mention the need to explicitly set '_serialize' to false for those two.

**Comment by josegonzalez** [comment]
Thats pretty fair. I think that would go in both the 3.0 migration docs as well as the View docs. Mind coming up with a pr for that?

**Comment by ADmad** [comment]
Closing as no change is required in app skeleton. Please open a PR / issue on the docs repo if required.
