### ISSUE TITLE
cake.css - duplicate rules

### ISSUE THREAD

**Issue by joshwyrick** [cakephp/app#451]
I found some duplicate CSS rules spread across `cake.css` that I think could be cleaned up, but I'm unsure what is "correct" for the default theme out of the box . I've grouped them together below to help with suggestions, or for anyone that would like to make the corrections.

~~~~
.form button:hover, .form button:focus {
    background: #7A6058;
    box-shadow: 0px 1px 1px rgba(0, 0, 0, 0.26) !important;
}
.form button:hover, .form button:focus {
    background: #BE840B;
    box-shadow: none;
}

.form button[type="submit"] {
    float: right;
    text-transform: uppercase;
    box-shadow: 0px 2px 5px rgba(0, 0, 0, 0.26);
}
.form button[type="submit"] {
    float: right;
    text-transform: uppercase;
    box-shadow: none;
}

.index table {
    margin-top: 2rem;
    border: 0;
    width: 100%;
    table-layout: fixed;
}
.index table {
    margin-top: 0rem;
    border: 0;
}

button {
    background: #8D6E65;
}
button {
    background: #966600;
}
~~~~

**Comment by inoas** [comment]
Correct is what has the same specificity (e.g. selector strength) and is defined later in the same file (and/or later in css files loaded later). 

You can find it out by using an inspector in Firefox or Crome. You can mock the tags (or to be precise, re-create the DOM structure so that it is picked up by the selector) in home.ctp (say <button> or `<div class="index"><table>`) and then inspect them to see what values they take.

**Comment by markstory** [comment]
There might be duplicate selectors from the CSS library (foundation) and the customizations we've made. Are the duplicate selectors you're seeing in the same file? Or is each instance of the selector in a different file?

**Comment by joshwyrick** [comment]
@markstory These are duplicates within `cake.css` (https://github.com/cakephp/app/blob/master/webroot/css/cake.css).

**Comment by markstory** [comment]
Ok. Then they could very easily be merged. Did you want to put together a pull request? If not I can take care of it.

**Comment by joshwyrick** [comment]
OK, I'll simply remove the first instances of each and send the pull request through.

**Comment by markstory** [comment]
Closing as a pull request is up now.
