### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by inoas** [cakephp/app#452]
Should Plugin::load('Migrations'); not be in bootstrap_cli together with bake?

**Comment by markstory** [comment]
It could. The webserver part of an app normally doesn't need migrations.

**Comment by inoas** [comment]
Closing as I quickly did the changes via GH

**Comment by BassemN** [comment]
Loading `Migrations` plugin only in CLI breaks migrations in [a non-shell environment](http://book.cakephp.org/3.0/en/migrations.html#running-migrations-in-a-non-shell-environment).
