### ISSUE TITLE
How to upgrade cakephp/app?

### ISSUE THREAD

**Issue by littleylv** [cakephp/app#462]
With my many thanks for your CakePHP.

I got ``composer update`` to update vendors in my application. But I'm wondering how to upgrade cakephp/app?

I found you guys make many wonderfull PRs to cakephp/app which could be very useful for everyone's application.

I created my app using:
``composer create-project --prefer-dist cakephp/app [app_name]``

**Comment by ADmad** [comment]
You will have to do the updates manually. Since this skeleton is a starting point for your app and the various files would have been modified as per your needs there isn't a way to provide automated upgrade.

**Comment by littleylv** [comment]
I got you. @ADmad
