### ISSUE TITLE
RFC - Bootstrap vs Foundation

### ISSUE THREAD

**Issue by andtxr** [cakephp/app#476]
This RFC is open to discuss about the adoption of Bootstrap over Foundation.

The discussion reference was opened in #475 

Nowadays there is a market preference for Bootstrap.

Particularly I think the mostly users would like this change.

Even the CakePHP project main websites are walking this direction.

What do you think?

**Comment by antograssiot** [comment]
I think that a php framework shouldn't care...
More seriously, it easy also easy enough to create your own template for bake. 
Then you can use whatever you want in your app.


So long story short, I'm not totally against the idea but won't push it nor spend time working on this.

**Comment by ADmad** [comment]
As long as people don't expect the HTML generated by the core helpers to be geared towards bootstrap I don't mind. It should stay css framework agnostic like it is currently.

**Comment by josegonzalez** [comment]
@andtxr what issues are there with the [friendsofcake/bootstrap-ui](https://github.com/FriendsOfCake/bootstrap-ui/) plugin? I'd be in favor of making that (or something like it) the default in 4.x, and moving our current "defaults" that like Foundation into a plugin as well. That way people can switch between the two at will.

**Comment by andtxr** [comment]
Following the reference, now we have two frameworks in the base code of the CakePHP app.

Taking into consideration the effort to standardize everything that already exists, it is easier to adapt the new Home template to use Foundation, right?

I do not remember, but the CSS of the baked templates depends on Foundation?

**Comment by josegonzalez** [comment]
Yeah, baked templates currently support Foundation afaik.

**Comment by andtxr** [comment]
@josegonzalez no issues, I actually love it. 😄 

The discussion is up due the referenced PR.

**Comment by josegonzalez** [comment]
Yeah, I guess we should refactor it to use Foundation since thats what we already depend upon.

**Comment by lorenzo** [comment]
The reason we used foundation is because it required no code changes in php in any of the helpers, back we we were doing 3.0; whereas bootstrap required big changes that would only work with bootstrap.

**Comment by josegonzalez** [comment]
Note: it's not just the cakephp/app repo that needs to be "updated". We also have to make helper changes - where we produce html output - as well as bake. This is highly invasive.

While I love bootstrap, we should take care to not break any existing functionality for users. For instance, I might have an older cakephp/app installation with new bake for creating a simple Crud admin for something. Moving to bootstrap would break that unnecessarily, causing a bad experience for our users.

@lorenzo has that situation changed since Cake3 was released? If it has - or will in Bootstrap4 - then moving will be a bit more feasible. Otherwise, I vote that we wait until Cake4.

**Comment by ADmad** [comment]
> has that situation changed since Cake3 was released? If it has - or will in Bootstrap4 - then moving will be a bit more feasible. Otherwise, I vote that we wait until Cake4.

I don't think the situation has changed. Bootstrap is bloat and requires adding lot of extra classes to get it's default styling.

**Comment by lorenzo** [comment]
@josegonzalez as you well pointed out, it is still a massive change. I used foundation just for the reason that it saved time, no code changes were needed and it looked very solid. Additionally, the use of a more agnostic html, allowed us to refine the extension mechanisms to create other ui libraries, like the one for bootstrap.

**Comment by inoas** [comment]
I suspect for 4.0 display: flex or display: grid can be used for the grid.

- http://caniuse.com/#feat=flexbox
- http://caniuse.com/#feat=css-grid

As for default styles we can use something like Marx https://github.com/mblode/marx which does not require any changes to markup or classes, e.g. our app skeleton and bake would become agnoistic.

That leaves total control to the app developer and we don't force anything down their throat.
Per app the developer can adopt to bootstrap-, ionic-, foundation or framework7-mixins or patch their layout to use twbs et al. div/class-soup.

**Comment by andtxr** [comment]
I also think that flexbox or css-grid is a good option for the future. Actually the best agnostic option. Default styling for buttons, lists, etc, is not a so hard task.

We have reached some conclusions:

- The process of adapting existing stuff to handle Bootstrap 3 would be onerous.
- Probably it would break many users compatibility.
- Maybe things can change with the arrival of Bootstrap 4, and if so, we can open this discussion again.

The base PR for this RFC was already finished and fixed, so I think we are done. 🕺

**Comment by dereuromark** [comment]
I agree - closing with PR https://github.com/cakephp/app/pull/478

**Comment by bravo-kernel** [comment]
👍🏼

**Comment by dereuromark** [comment]
@bravo-kernel Those emoji are not readable by most people and browsers

**Comment by ADmad** [comment]
@bravo-kernel Just use the emoji codes like `:+1:` supported by GH and everyone's happy :smile:

**Comment by bravo-kernel** [comment]
✅
