### ISSUE TITLE
RFC: Update default css

### ISSUE THREAD

**Issue by cleptric** [cakephp/app#481]
As CakePHP has a pretty neat design since 3.3, I'm always a little bit disappointed to see this "not-so-cool" looking design when I bake my templates.
Can we update the css and use more of the "cake-red" instead of the green?
Maybe some additional eye candy here and there ;)
If this is ok with you, I can give it a try.

**Comment by markstory** [comment]
I don't know if @phpnut has any designs from the rebranding designer. If not switching green for red would be a great place to start.

**Comment by inoas** [comment]
The bake templates should not rely on external font resources, IMHO. A local copy of Raleway or whatever it is and a swap on the color palette would do a lot 👍

**Comment by cleptric** [comment]
As a PR is already open and additional a new layout will be provided in the future, I'll close this
