### ISSUE TITLE
Session timeout units

### ISSUE THREAD

**Issue by LubosRemplik** [cakephp/app#484]
https://github.com/cakephp/app/blob/master/config/app.default.php#L317

Is it really in minutes, not in seconds? If minutes are correct, don't you think session.cookie_lifetime should be in minutes too? (same unit), see doc https://book.cakephp.org/3.0/en/development/sessions.html#session-configuration

**Comment by cleptric** [comment]
Yes minutes are correct as `Session::__construct` multiples the `timeout` value by 60.
I guess they chose seconds for the `session.cookie_lifetime` as it's easier to just `ini_set ` it without any calculation.
I think it would be more consistent to use seconds for the `timeout`, too, but changing this won't be BC and should be discussed over at the cakephp issue tracker.
