### ISSUE TITLE
need to new release

### ISSUE THREAD

**Issue by saeideng** [cakephp/app#494]
Needs to new release for new installs for cakephp 3.4 with composer create-project ....

**Comment by cleptric** [comment]
This already happened with 1dc35cec1b1f671115c47b17008e2af9491f1a97
The packagist repo also lists cakephp/app 3.4.0

**Comment by saeideng** [comment]
Not enough :)

**Comment by markstory** [comment]
What do you mean by 'not enough' @saeideng ?

**Comment by saeideng** [comment]
We can not use composer create-project ... now for using the cake3.4
Because in latest stable ver used cake 3.3.x

**Comment by cleptric** [comment]
It installs cakephp/cakephp 3.4.1 when running `composer create-project --prefer-dist cakephp/app`

![screen shot 2017-02-19 at 14 15 40](https://cloud.githubusercontent.com/assets/6617432/23104672/b33d9284-f6d2-11e6-825b-c52fe688d099.png)

**Comment by saeideng** [comment]
But for me that trying to install cakephp 3.3.15
I dont know why

**Comment by cleptric** [comment]
Have you tried `composer clearcache`?

**Comment by antograssiot** [comment]
@saeideng you're not using php5.5 right ?

**Comment by saeideng** [comment]
@antograssiot i tested first in php 5.5
I think you are right
After that i install it with composer install but after upgrating php

**Comment by saeideng** [comment]
That means new programs with php 5.5 receive cakephp  3.3?

**Comment by cleptric** [comment]
Just tested it with php5.5. Indeed, it installs `cakephp/app (3.3.6)` with `cakephp\cakephp (3.3.15)`, which is totally right, as cakephp 3.4 requires php5.6

**Comment by antograssiot** [comment]
You should read the migration guide.
https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html

The composer.json also makes it quite clear https://github.com/cakephp/app/blob/master/composer.json#L8
