### ISSUE TITLE
Deprecated methods in bootstrap.php

### ISSUE THREAD

**Issue by ironbone** [cakephp/app#496]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version:3.4.

* Platform and Target: 

### What you did
php composer.phar create-project --prefer-dist cakephp/app my_app_name

### What happened
in bootstrap.php there are the following lines with deprecated methods:
Cache::config(Configure::consume('Cache'));
ConnectionManager::config(Configure::consume('Datasources'));
Email::configTransport(Configure::consume('EmailTransport'));
Email::config(Configure::consume('Email'));
Log::config(Configure::consume('Log'));
Security::salt(Configure::consume('Security.salt'));

### What you expected to happen
Use non deprecated methods

**Comment by cleptric** [comment]
Thanks for the report 👍
