### ISSUE TITLE
3.4.2 Log queries Datasources.default.log=true via scope queriesLog exclusively in queries.sql

### ISSUE THREAD

**Issue by inoas** [cakephp/app#500]
This is a (multiple allowed):

* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.4.2

### What you did
~~When developing APIs, set 'log' to true. My debug.log was filled with sql queries.~~

Using `queriesLog` scope to log sql queries.

### What you expected to happen
~~Being able to set 'log' to 'sql.log' so that it would write to logs/sql.log~~
- The logs still appear in debug.log
- The query log file cannot be named with extension .sql for automatic syntax highlightning in editors but always appends `.log`.

**Comment by markstory** [comment]
The `log` flag is a boolean. You would need to configure a logger to capture the `queriesLog` scope and direct it to the correct file.

**Comment by inoas** [comment]
I can add following example to the docs. It works(tm) however has one issue. I have 2 little problems:

1. debug.log still shows all the sql queries. It probably fetches all scopes?! Is there a way to excludeScope?

2. I named my file "queries.log.sql" and the file created was "queries.log.sql.log" ;-). If it was named .sql my text editor could even pick it up and syntax-highlight the queries.

Any ideas for any of those two points?

If there are no objections I will add a docs PR to add this as an example:

```php
<?php
    /**
     * Configures logging options
     */
    'Log' => [
        'queriesLog' => [
            'className' => 'Cake\Log\Engine\FileLog',
            'path' => LOGS,
            'file' => 'queries.log',
            'scopes' => ['queriesLog'],
            'url' => env('LOG_QUERIES_URL', null),
        ],
        'debug' => [
            'className' => 'Cake\Log\Engine\FileLog',
//...
```

p.s.: `tail -f general.log` is nice but requires you to enable your general.log in mysqld etc... so this can come really handy with the increased API related projects everyone is doing now.:

**Comment by markstory** [comment]
> debug.log still shows all the sql queries. It probably fetches all scopes?! Is there a way to excludeScope?

No.

> I named my file queries.log.sql and the file created was queries.log.sql.log ;-). If I could add the extension .sql my text editor could even pick it up and syntax-highlight the queries

File logging always appends `.log` from what I remember. You might just have to live with that.

**Comment by inoas** [comment]
I will but maybe for 4.x this could change to work like `$this->Html->css()` where you can leave out the extension, if you do `.log` is assumed.

**Comment by dereuromark** [comment]
Is this still worth persuing? Otherwise I would vote for closing.

**Comment by inoas** [comment]
> debug.log still shows all the sql queries. It probably fetches all scopes?! Is there a way to excludeScope?

For me it separates now... (aka the queries do not show in debug.log anymore; possibly for quite a while as it did not bother me again).

PR is here: https://github.com/cakephp/app/pull/534
