### ISSUE TITLE
Integration tests - Action Controller::() could not be found

### ISSUE THREAD

**Issue by styks1987** [cakephp/app#509]
This is a (multiple allowed):

* [x] bug

* CakePHP Application Skeleton Version: 3.4.6
* Platform and Target: LAMP

### What you did
Trying to do simple integration tests

    public function testLogin()
    {
        $this->get('/users/login');
        $this->assertResponseOk();
        $this->assertResponseCode(200);
        $this->assertNoRedirect();
    }

### What happened
    exception 'Cake\Controller\Exception\MissingActionException' with message 
    'Action Controller::() could not be found, or is not accessible.

### Fixing it
I found that these lines where in an older version but not in the new bootstrap.php. Adding them in fixed the issue.

    DispatcherFactory::add('Asset');
    DispatcherFactory::add('Routing');
    DispatcherFactory::add('ControllerFactory');

**Comment by styks1987** [comment]
Dakota pointed out to me that the new version does not use dispatcher factory and that integration tests should automatically detect the existence of Application.php. However, this does not appear to be happening.

When I force it it works.

    $this->useHttpServer(true);

But it does not autodetect my Application.php and use the new psr-7 middleware setup.

**Comment by markstory** [comment]
How can someone reproduce this? Tests using the middleware stack work in the applications I have.

**Comment by styks1987** [comment]
Could you tell me where the code is that is supposed to autodetect the Application.php for integration tests? I can debug to find why my application isn't finding that.

**Comment by styks1987** [comment]
NVM. I found that it is in the setUp function and I was not calling parent::setUp. Sorry for the noise.
