### ISSUE TITLE
Inconvenient .gitignore for contributing

### ISSUE THREAD

**Issue by ravage84** [cakephp/app#510]
The [.gitignore](https://github.com/cakephp/app/blob/3.4.2/.gitignore) file in its current state is totally inconvenient for contributing.

Due to a few changes ([1](https://github.com/cakephp/app/commit/cd7efc5c1679f3f4d0c927a5386bd0d71c98ae1e), [2](https://github.com/cakephp/app/commit/9509d503eacc7d7e33d36d7b1c1ae02388ea7c9e)), the .gitignore became from [totally convenient for contributing](https://github.com/cakephp/app/commit/5d6a60c84c5958c2061c01ea89fdf25fc19ab388) to totally inconventient as now one gets several files prompted for being versioned that do not need to be versioned for an open source project.

Those files are:
- .idea/* (PhpStorm project folder)
- bin/boris & bin/boris.bat
- composer.lock
- plugins/DebugKit/*

I understand we have to choose between being optimized for open source contributions or for project usage. I would prefer the first, as the inconvenience is bigger right now. Currently every open source contributor has to **make sure he/she does not commit one of the files above every time** he/she wants to contribute. If we would optimise for OSS contributions, the only thing a developer has to do after setting up his/her new app **is to adjust the .gitignore to his/her very specific needs once**.

Also, I know some say IDE specific folders such as .idea and typical PHP tool files such as *.phar should be ignored through one's global .gitignore file.  This is all fine and dandy, but the truth I observed over the last few years is that most developers do not set their global .gitignore file properly (including me). It's much more convenient if this is setup by project/repo.

For example, internally we started to version some files in the .idea folder for internal projects recently, while we do not version them for OSS projects.

**Comment by dereuromark** [comment]
Actually, excluding 

    composer.lock

by default is a bad practice, also for app skeleton (as boilerplate for a new project).

.idea is pretty proprietary (but I would be fine adding this again, doesnt hurt).
I dont know about the other two.

**Comment by ravage84** [comment]
@dereuromark  I do not see why excluding the ``composer.lock`` **in this particular case** is bad practise. I can agree it is in other cases, though.

But here, we have two clear usage scenarios:

a) OSS contributions aka the "CakePHP App Template repo"
b) project usage aka internal

For a) we can either add the ``composer.lock`` to be versioned and then we do not need to exclude it or we do not add it but should then exclude it as **it will be prompted to be added every time**, otherwise.

For b) it depends on the company conventions, though I also would say in this case it's very likely bad practise.

**Comment by dereuromark** [comment]
We could most likely just revert https://github.com/cakephp/app/commit/cd7efc5c1679f3f4d0c927a5386bd0d71c98ae1e
as that file and its content doesnt hurt and projects would have to add 90% of those again anyway.
I think removing them was not a good idea in the first place.

**Comment by inoas** [comment]
Regarding cd7efc5 :
```
-# OS generated files #
-######################
-.DS_Store
-.DS_Store?
-._*
-.Spotlight-V100
-.Trashes
-Icon?
-ehthumbs.db
-Thumbs.db
```
... should defiantly stay?

**Comment by dereuromark** [comment]
Do you want to make a PR here for 3.5?
It is pretty clear that those should stay for the sake of every one :)

**Comment by inoas** [comment]
These are debate-able.
https://github.com/cakephp/app/pull/532/files#diff-a084b794bc0759e7a6b77810e01874f2R32

However I think we should have sufficient out of the box support for:
- vim
- textmate
- sublime
- atom
- PHPStorm / JetBrains
- Eclipse/Aptana
- Xcode
- Netbeans
- Emacs
- Common cache directories for transpilers (Elm, Coffescript, Sass, Scss, Less, Stylus)

If we cannot find a way to do that I'd say we should either support nothing or just the bare minimum: vim (Disclaimer: I am a textmate user).

**Comment by dereuromark** [comment]
PR open. We can discuss there.
