### ISSUE TITLE
Fatal error:  Class 'Cake\TestSuite\IntegrationTestCase' not found

### ISSUE THREAD

**Issue by anuj9196** [cakephp/app#522]
* [x] bug

* CakePHP Application Skeleton Version: CakePHP 3.4.*
* Platform and Target: Windows 10, PhpStorm IDE.

### What you did
Created a new project and clicked **run project** icon in PhpStorm IDE

### What happened
Before running project, test was initiated and error was flashed
```
C:\xampp\php\php.exe C:/Users/user/AppData/Local/Temp/ide-phpunit.php --no-configuration C:\Users\user\PhpstormProjects\untitled2
Testing started at 11:53 AM ...


Fatal error: Class 'Cake\TestSuite\IntegrationTestCase' not found in C:\Users\user\PhpstormProjects\untitled2\tests\TestCase\ApplicationTest.php on line 28PHP Fatal error:  Class 'Cake\TestSuite\IntegrationTestCase' not found in C:\Users\user\PhpstormProjects\untitled2\tests\TestCase\ApplicationTest.php on line 28

Process finished with exit code 255

```

**Here `untitled2` is the project name**

### What you expected to happen
Successfully pass all tests because this is newly created project and no file has been touched

**Comment by ravage84** [comment]
We work with Windows 7 & 10 and with PhpStorm 2017.x
It should work just fine. Are you sure you have setup everything correctly?

Here a video that might help:
https://www.youtube.com/watch?v=NztroIqNBZA&feature=youtu.be

**Comment by dereuromark** [comment]
Also see https://github.com/FriendsOfCake/awesome-cakephp#demo (e.g. Sandbox) with their working tests all working fine, also on windows.
It must be a user error, not a framework issue.

**Comment by anuj9196** [comment]
Yes, it was an user error. I had to manually install PhpUnit 
```
composer require --dev phpunit/phpunit:"^5.7|^6.0"
```

I thought of it will come installed default by CakePHP because it has inbuilt test functionality

**Comment by dereuromark** [comment]
Please see
https://github.com/cakephp/app/blob/master/composer.json#L23

Some of us - including me - like to use the phar files to not further add dependencies here into vendor.
That's why it is a recommendation rather than a must-have default.
