### ISSUE TITLE
Fatal Error, Installer::postInstall, ShellDispatcher

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/app#525]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 3.4.2 via composer
* Platform and Target: CLI

### What you did
    ┌─[jlroberts@Jeffreys-iMac]─[~/Projects/JeffreyLRobertsCom/CakePHPKitchen]
    └──╼ composer create-project --prefer-dist cakephp/app bakeTestApp

    Installing cakephp/app (3.4.2)
      - Installing cakephp/app (3.4.2): Loading from cache
    Created project in bakeTestApp
    Loading composer repositories with package information
    Updating dependencies (including require-dev)
    Package operations: 35 installs, 0 updates, 0 removals
    ...
    Writing lock file
    Generating autoload files
    > Cake\Composer\Installer\PluginInstaller::postAutoloadDump
    > App\Console\Installer::postInstall
    Created `config/app.php` file
    Set Folder Permissions ? (Default to Y) [Y,n]?
    Permissions set on ...
    Updated Security.salt value in config/app.php
    
    ┌─[jlroberts@Jeffreys-iMac]─[~/Projects/JeffreyLRobertsCom/CakePHPKitchen]
    └──╼ cd bakeTestApp/
    
    ┌─[jlroberts@Jeffreys-iMac]─[~/Projects/JeffreyLRobertsCom/CakePHPKitchen/bakeTestApp]
    └──╼ subl .

Code

    public static function postInstall(Event $event)
    {
        ...

        $bakeDatabaseConfig = $io->askAndValidate(
            '<info>Bake Database Config ? (Default to Y)</info> [<comment>Y,n</comment>]? ',
            $validator,
            10,
            'Y'
        );

        $shell = new ShellDispatcher();

        if (in_array($bakeDatabaseConfig, ['Y', 'y'])) {

            // cake bake database
            $shell->dispatch([
                'command' => 'bake database',
                'extra' => []
            ]);
        }
    ...

### What happened
Execution
    
    ┌─[jlroberts@Jeffreys-iMac]─[~/Projects/JeffreyLRobertsCom/CakePHPKitchen/bakeTestApp]
    └──╼ composer run-script post-install-cmd

Output and Error
    
    > App\Console\Installer::postInstall
    Set Folder Permissions ? (Default to Y) [Y,n]?
    Bake Database Config ? (Default to Y) [Y,n]?
    PHP Fatal error:  Call to undefined function Cake\Console\namespaceSplit() in /Users/jlroberts/Projects/JeffreyLRobertsCom/CakePHPKitchen/bakeTestApp/vendor/cakephp/cakephp/src/Console/Shell.php on line 174
    
    Fatal error: Call to undefined function Cake\Console\namespaceSplit() in /Users/jlroberts/Projects/JeffreyLRobertsCom/CakePHPKitchen/bakeTestApp/vendor/cakephp/cakephp/src/Console/Shell.php on line 174

### What you expected to happen

I expected to be asked the bake database questions...

Side Note: I also sorta expected to be able to do this, I did it naturally...

    ┌─[✗]─[jlroberts@Jeffreys-iMac]─[~/Projects/JeffreyLRobertsCom/CakePHPKitchen/bakeTestApp]
    └──╼ git diff src/Console/Installer.php
    Not a git repository
    To compare two paths outside a working tree:
    usage: git diff [--no-index] <path> <path>

**Comment by jeffreyroberts** [comment]
It appears that src/Core/functions.php is not being auto-loaded, and im new to composer, im not sure how this autoloader works yet, while this post is marinating, im going to be reviewing the auto-loader process... just seems like this should have worked out of the box is all... thank you all so much for your contributions to the community =]

**Comment by cleptric** [comment]
You should not alter the `Installer.php` file shipped by this repo, unless you want to change something related to the actual creation of the app skeleton.
If you want to create custom shells, have a look at https://book.cakephp.org/3.0/en/console-and-shells.html
Also, AFAIK, `bake` dosen't have a command to crate a database 🙂 
Regarding your git question, composer doesn't create a new git repo for you. Run `git init` inside your app folder to create one.

**Comment by markstory** [comment]
Composer doesn't autoload CakePHP files. You'll need to do that yourself.

**Comment by jeffreyroberts** [comment]
@cleptric I have forked the app skeleton and I am modifying it for use in all my future projects... To make the install process easier I was going to do things like bake database, run my migrations for plugins, and any other install scripts from the Installer.php

I just joined freenode.com to ask questions...

@cleptric and lol, it sure doesnt, i could have swore there was a bake command to create the database file, looks like that might have changed, either way, i think you guys get the idea, the thing i dont understand is

if composer doesn't autoload the files, then something is autoloading these use statements

     use Cake\Utility\Security;
     use Composer\Script\Event;
     use Exception;
     use Cake\Console\ShellDispatcher;

now if those classes can loaded, then why isn't the src/Core/functions.php file being loaded?

I am going to ask on IRC and get back to reviewing this auto-loader...

**Comment by jeffreyroberts** [comment]
@markstory Are you sure that cakephp/src/Core/functions.php shouldn't be loaded by the composer autoloader? ... sorry about the dupe question, I know you already answered, and I am sorry for asking again, I asked on freenode, and they told me to require the file... which i tried, and immediately got 

    Use of undefined constant APP - assumed 'APP'

which just means rabbit hole and not the way to go IMO... im going to start from scratch with the composer autoloader tutorial now

**Comment by ADmad** [comment]
@jefferyroberts Please post a question on the forum if you need help understanding things. This issue tracker is not the place for help questions.

**Comment by jeffreyroberts** [comment]
ok, thank you
