### ISSUE TITLE
Error reading dir files

### ISSUE THREAD

**Issue by anuj9196** [cakephp/app#527]
This is a (multiple allowed):

* [x] bug

* CakePHP Application Skeleton Version: 3.4.3
* Platform and Target: Apache Server.

### What you did
I have to read files from a directory on ftp server
```
$d = dir($source_directory);

// do this for each file in the directory
while ($file = $d->read()) {
    ....
    ....
}
```

### What happened
CakePHP giving Fatal error
```
Call to a member function read() on boolean
```

### What you expected to happen
read() is function of PHP to read files from a directory http://php.net/manual/en/function.dir.php
CakePHP should not find any model for this read() function

**Comment by ADmad** [comment]
[dir()](http://in2.php.net/manual/en/function.dir.php) can return `false`. Which is mostly what's happening in your case and causing the error. CakePHP can't augment how core PHP works.
