### ISSUE TITLE
Improve app/config/schema/sessions.sql

### ISSUE THREAD

**Issue by inoas** [cakephp/app#535]
Suggestion:

```sql
CREATE TABLE `sessions` (
  `id` char(40) CHARACTER SET ascii COLLATE ascii_bin NOT NULL,
  `created` datetime DEFAULT CURRENT_TIMESTAMP,
  `modified` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `data` blob DEFAULT NULL,
  `expires` int(11) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
```

Ref: https://book.cakephp.org/3.0/en/development/sessions.html#database-sessions
Ref: https://github.com/cakephp/app/blob/master/config/schema/sessions.sql

**Open Questions**

- Did the sessions.sql schema ran on PostGreSQL before?
- Should it? Should/could we supply multiple sessions.sql-files depending on the adapter?
- What is the max length the ID field can take... is it really char(40)?

**Comment by inoas** [comment]
Also in DatabaseSession.php:

```
    /**
     * Helper function called on write for database sessions.
     *
     * @param int $id ID that uniquely identifies session in database
     * @param mixed $data The value of the data to be saved.
     * @return bool True for successful write, false otherwise.
     */
    public function write($id, $data)
    {
```

... but `$id` is really a string, isn't it?

**Comment by markstory** [comment]
> Did the sessions.sql schema ran on PostGreSQL before?

I don't think so, as it has been a blob field for quite some time.

> ... but $id is not of type int, but of string, isn't it?

Yes it is.

**Comment by inoas** [comment]
`blob`? it is still text in cakephp/app just not in cakephp/docs...

PRs are open, ... closing.
