### ISSUE TITLE
Should Csrf be removed from AppController and placed in Application instead?

### ISSUE THREAD

**Issue by MCF** [cakephp/app#540]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 9eae2648da9dae7511f4ca9070a2cce1114b6ddd

Just wondering if the app should be updated to replace the CsrfComponent (commented out) in the AppController with the new CSRF middleware in Application instead?  Or am I misunderstanding the 3.5 upgrade guide?

**Comment by markstory** [comment]
@MCF CsrfMiddleware should likely be applied as a scoped middleware. This is something that was missed in preparation for 3.5 though.

**Comment by MCF** [comment]
Thanks @markstory, I noted the deprecation of the component in the upgrade guide but was having trouble finding documentation on how the CsrfMIddleware works.  It looks like it is pretty new and the documentation is still pretty thin.  Just checking out the app in case there was any additional guidance and I thought I would mention that it needed to be updated.

**Comment by markstory** [comment]
The existing documentation [can be found here](https://book.cakephp.org/3.0/en/controllers/middleware.html#csrf-middleware) what did you find missing/unclear as I'd like to improve the docs if possible.

**Comment by MCF** [comment]
I was trying to understand how to turn off Csrf for the occasional action.  In complicated interactive forms it can be difficult to have it work with Csrf (Component or Middleware).

It would also be nice if there was some documentation about how Csrf can be made to work with these kinds of forms that are modified via javascript, rather than being disabled entirely in those cases.  For example as a form is filled out items may be enabled/disabled or added/removed depending on choices made earlier in the form.

**Comment by markstory** [comment]
> I was trying to understand how to turn off Csrf for the occasional action. In complicated interactive forms it can be difficult to have it work with Csrf (Component or Middleware).

You would need to use routing scopes to only enable it for certain parts of your application.

> It would also be nice if there was some documentation about how Csrf can be made to work with these kinds of forms that are modified via javascript, rather than being disabled entirely in those cases. 

Wouldn't the CSRF token be sent along with the modified form? Are you thinking of SecurityComponent (which prevents form tampering)?

**Comment by MCF** [comment]
Yes, you are right.  I am conflatting the Security component and the Csrf components a bit here.  Here is a sample snippet of code from a beforeFilter in one of my controllers:

```PHP
        $action = $this->request->getParam('action');
        if (in_array($action, ['apply', 'remove'])) {
            $this->eventManager()->off($this->Csrf);
        }

        if (in_array($this->request->getParam('action'), ['add', 'edit'])) {
            $this->Security->setConfig('unlockedFields', ['part_number_id']);
        }
```

Now that I'm having another look at this I think the Csrf disabling is because the `apply` and `remove` actions are Ajax request endpoints and I hadn't had time to sort out how to make Ajax play nicely with the CsrfComponent.

Apologies for going on about this without looking more carefully at my code.  I'll have a look at the routing scopes as you suggested.

**Comment by gonzela2006** [comment]
@MCF Did you find a way to disable Security and Csrf components for an action?

**Comment by MCF** [comment]
@gonzela2006, the code snippet in my previous comment has an example of how to disable Csrf for the `apply` and `remove` actions, and how to _not_ use the security component for the `part_number_id` field with the `add` and `edit` actions.  That code is from a controller's beforeFilter function and so only applies to that controller.

[Another discussion](https://stackoverflow.com/questions/31018156/disabling-csrf-on-a-specific-action-cakephp-3) of Csrf disabling and [CakePHP docs](https://book.cakephp.org/3.0/en/controllers/components/security.html#disabling-security-component-for-specific-actions) for unlockedFields.

**Comment by gonzela2006** [comment]
@MCF I'm so sorry for not being clear, if I'm using CsrfMiddleware(as Csrf component deprecated), how can I disable the Csrf for an action in this case?

**Comment by MCF** [comment]
@gonzela2006, sorry no,  I have not had a chance to sort out how the middleware version of Csrf can be adjusted for this same type of problem.

**Comment by markstory** [comment]
Is the use case that you have a single controller action in that requires no CSRF protection, while the other controller actions do need CSRF protection.

**Comment by MCF** [comment]
Short answer yes.  Longer answer is that I just needed to get a legacy application working and it had a few ajax form submits that did not play nicely with CSRF, so I turned off CSRF for those few actions.  The real long term solution seems to be to use the `X-CSRF-Token` header in the ajax request and supply the CSRF token from the cookie on the client side.

But it might be nice to have the ability to _not_ use CSRF for a few select actions, while leaving it on as default for the rest of the site.

**Comment by saeideng** [comment]
>Is the use case that you have a single controller action in that requires no CSRF protection, while the other controller actions do need CSRF protection.

for example when data passed from _bank_ to the one action

**Comment by markstory** [comment]
Perhaps the middleware should have additional configuration options to exempt URL patterns? Middleware is applied well before controllers are invoked, and controllers can't 'see' middleware either.

**Comment by MCF** [comment]
Yes something like that would be convenient for my use case at least.  I think the pattern of turning on Csrf site wide, then disabling it for a few select end points is fairly common.  At least there is a fair bit of chatter on the internet about how to do that with the older Csrf Component.  I guess it boils down to Csrf for "most" is better than not at all.

My initial read on routing scopes caused me to put the Csrf middleware on the back burner for now. I'm still using the Component.

**Comment by markstory** [comment]
I had originally hoped that people would be able to use routing scopes to apply CSRF checks to the relevant controllers. I'm guessing that is not an option in your application.

Would regexp patterns be a reasonable way to match URLs that should not have CSRF applied to them?

**Comment by saeideng** [comment]
in `routes.php` we able to removing some of middlewares?

**Comment by markstory** [comment]
@saeideng That is how scoped middleware works. The middleware defined in each scope are the only middleware that is applied to routes within that scope. If CSRF was not in the list of middleware for a scope (or that scope's parents) it would not be applied.

**Comment by MCF** [comment]
@markstory the reason I have not attempted to use the Csrf middleware and scoped routes is just a matter of priorities.  I will work through it sometime, just haven't had time right now.

What I was trying to say above is that it did not look like a 10 minute fix to switch from the Component to the Middleware, given how I was configuring the component for some actions.   I wasn't saying that it scoped routes would not work - just haven't tried yet.

**Comment by markstory** [comment]
Ok. I agree it is not a quick change over for a medium to large application.

**Comment by gonzela2006** [comment]
@markstory Is there any example to disable CSRF or Security middleware from routes?

**Comment by markstory** [comment]
The [documentation for scoped middleware](https://book.cakephp.org/3.0/en/development/routing.html#connecting-scoped-middleware) cover scopes with/without middleware.  You don't 'disable' middleware with scoped middleware. Instead you open a new scope that *lacks* middleware.

**Comment by jadedcore** [comment]
Currently I have not enabled CSRF Middleware for certain actions in the src/Application.php file.

```
    $uri = $_SERVER['REQUEST_URI'];
    if ($uri !== '/url/to/action') {
        $middleware->add($csrf);
    }
```

I plan to investigate the Routing Scopes for doing this in the future, but I'm still trying to understand how this is a step forward from Cake 2 where I could easily enable/disable CSRF protection from the controller that it was applicable to.

**Comment by HorlogeSkynet** [comment]
Hello over here,

Pretty interested in this, does someone have an idea to **NOT** enable a middleware for a specific route, while enabling it for all the other (in order to reproduce the `unlockFields` behavior) properly ?

Other request : Should not this issue be moved to the `cakephp` repository ?
'cause I ended here after having Google'd it and encountered this : http://discourse.cakephp.org/t/csrf-middleware/3292 (a big thanks to @MCF btw !)...

Have a good day all of you,
Bye 👋

**Comment by markstory** [comment]
@HorlogeSkynet That can be done via scoped middleware in your routes file.

```php
// Inside a route scope, with csrf registered as a middleware
$routes->scope('/articles', ['controller' => 'Articles'], function($routes) {
  $routes->applyMiddleware('csrf');

  $routes->get('/:id', ['action' => 'view']);
  // Other routes that need csrf go here.
});
$routes->scope('/articles', ['controller' => 'Articles'], function($routes) {
  // No csrf here.
  $routes->delete('/:id', ['action' => 'delete']);
});
```

**Comment by HorlogeSkynet** [comment]
Oh well @markstory thank you for your quick answer, and I take the benefit of this message to apologize : I confounded (again) the `Csrf` and the `Security` components... So sorry, no need of `unlockedFields` over here.
But still, your post resumes well how we should do it, thanks again 👌

Bye

**Comment by dereuromark** [comment]
Can this be closed?

**Comment by MCF** [comment]
I don't want to be a pain, but doesn't the underlying issue still exist in the app?  The deprecated Csrf component is still shown in the AppController:

https://github.com/cakephp/app/blob/master/src/Controller/AppController.php#L52

Nothing in the Application.php showing the new Csrf middleware.

**Comment by markstory** [comment]
Good point, we can get that fixed up.

**Comment by LubosRemplik** [comment]
I think we can close this, #616 added csrf into application and can't see it as component in app controller any more

**Comment by yosus** [comment]
I am also trying to disable the CSRF for a specific controller/action on Cakephp 3-6-7.  The docs don't say much about disabling CSRF. Would be nice to have back the '$this->getEventManager()->off($this->Csrf);'.

I keep on getting the error 'CSRF token mismatch. Cake\Http\Exception\InvalidCsrfTokenException'. My routes.php file is as such. Am I missing something else ? 


````
<?php

// config/routes.php
use Cake\Core\Plugin;
use Cake\Routing\RouteBuilder;
use Cake\Routing\Router;
use Cake\Routing\Route\DashedRoute;


Router::defaultRouteClass(DashedRoute::class);

Router::scope('/', function (RouteBuilder $routes) {

	$routes->scope('/recipes', ['controller' => 'Recipes'], function($routes) {
	  // No csrf here.
	  $routes->delete('/:id', ['action' => 'delete']);
	});

    $routes->connect('/', ['controller' => 'Pages', 'action' => 'display', 'home']);
    $routes->connect('/pages/*', ['controller' => 'Pages', 'action' => 'display']);
    $routes->fallbacks(DashedRoute::class);
});

**Comment by yosus** [comment]
Thanks Garas. I tried it with 'ApiController.php', and a http-POST still  shows the CSRF error. No problem with http-GET request.

Is there a way to disable CSRF all together ?

**Comment by garas** [comment]
If you have `CsrfProtectionMiddleware` in `Application`, then remove it from there because middlewares in `Application` are always applied.

You need to `applyMiddleware()` in scopes with CSRF and without `applyMiddleware()` in a scopes to skip this middleware.

**Comment by yosus** [comment]
Thanks garas. After removing the csrf  in Application.php, it is working now. Those who want to disable a whole controller :

```
Router::scope('/', function (RouteBuilder $routes) {
     // no csrf routes
    $routes->connect(  '/no-csrf/:action/', ['controller' => 'Api'  ]   );
});
`
