### ISSUE TITLE
Response::type() within AppController's beforeRender()

### ISSUE THREAD

**Issue by HorlogeSkynet** [cakephp/app#555]
This is a (multiple allowed):

* [ ] bug
* [X] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: CakePHP 3.5.3

### What I did
I was just looking at the [**3.4 migration guide**](https://book.cakephp.org/3.0/en/appendices/3-4-migration-guide.html#request-response-deprecations)...

### What happened
... when I saw that `Response::type()` had been deprecated and should be replaced by `Response::withType()`.

### What I expected to happen
But when I looked into the new app skeleton provided here, the old `type()` method is still used within the `AppController`'s `beforeRender()` (_JSON / XML_ detection).
Should not this be changed ?

A big thanks 👋

PS : I've dug a bit the WWW, but didn't find a thing about that, am I misunderstanding ?

**Comment by markstory** [comment]
>  Should not this be changed ?

Yes it should. We've just not had a chance to get to it yet. Any chance you could send a pull request to fix this?

**Comment by HorlogeSkynet** [comment]
I'll try, I keep you posted 👍 
Thanks for the confirmation

**Comment by HughbertD** [comment]
I might be missing something here but where does it say that Response::type() is deprecated? 
https://api.cakephp.org/3.4/class-Cake.Http.Response.html#_type
https://api.cakephp.org/3.5/class-Cake.Http.Response.html#_type

The docs don't appear to indicate that. 

Plus, the example in skeleton app is attempting to sniff out the requested type, and I don't think withType would be suitable for this

**Comment by HorlogeSkynet** [comment]
Hello, this in the 3.4 Migration Guide : 

> `Response::type()` would become `Response::withType()`

But you're right, it's not mentioned in the API nor the Book...

I've managed to get a workaround with the `RequestHandler` component, let me do some more tests and a PR will be proposed within some hours 👍

**Comment by markstory** [comment]
Close as a pull request is open now.
