### ISSUE TITLE
Webroot for plugin with hypen does not work

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/app#560]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 3.4.2
* Platform and Target: PHP, MySQL, OS X

### What you did
I baked two plugins, one named `Elite` and one named `EndUsers`

I then placed a text file in `plugins/EndUsers/webroot/test.txt` and a copy of that file in `plugins/Elite/webroot/test.txt`

### What happened
I visited my url `http://localhost:9001/elite/test.txt` and got back this

![screen shot 2017-10-23 at 9 21 03 pm](https://user-images.githubusercontent.com/2320614/31920610-20360138-b838-11e7-9f0d-d8d359f41245.png)

I then visited `http://localhost:9001/end-users/test.txt` and got back this

![screen shot 2017-10-23 at 9 21 12 pm](https://user-images.githubusercontent.com/2320614/31920630-34e45ce2-b838-11e7-9487-98b7ff96a9ef.png)

### What you expected to happen
I expected when I visited the /end-users/test.txt url to have the test.txt file served...

I have created a sample project to reproduce the issue, you can find it below

https://github.com/CakePHPKitchen/CakePHP-Plugin-Webroot-Issue

**Comment by markstory** [comment]
Plugin webroots use `_` as their separator. If you want a different separator you'll need to replace the `AssetMiddleware`.
