### ISSUE TITLE
Use cakephps skeleton app in another project, using composer

### ISSUE THREAD

**Issue by Snorvarg** [cakephp/app#573]
Hi, 
I would like to base a project I have on the cakephp/app repository and think about using composer to achieve this. 

What would be the best way to do it? The straight-forward solution would be to download the entire cakephp/app, add my files, and upload it as a new project. But that would make it a bit difficult to update it when you guys release new versions. 

How can I create a composer.json which are downloading/installing the cakephp/app files, and then download my own files, and move them into the correct positions? 

Guess I could use the scripting possibilities that comes with composer, but the problem with this is that I also would like to let users be able to download my project as a zip-file from github. 

Any general advice on these topics?

**Comment by dereuromark** [comment]
Just composer create a new project and then migrate your project

---

This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Comment by Snorvarg** [comment]
Dude, thanks a bunch! And sorry for misusing the forum, I was lost. :)
