### ISSUE TITLE
All Errors Are Now "An Internal Server Error Occurred"

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/app#574]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 3.5.10
* Platform and Target: cake server, mysql, os x

### What you did
Somehow all errors are now an internal server error, I have no idea what I could have changed to make this happen, I truly need some help here...

### What happened
No matter what type of error it is, it is an internal server error, and I get no cake debug output anymore

### What you expected to happen
cake debug output with stacktrace

### Please Help
What information can I provide to you to help figure out how to get the cake debug information back?

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!

**Comment by thinkingmedia** [comment]
Change `debug` to `true` in `app/config/app.php` as per the documentation.

https://book.cakephp.org/3.0/en/development/configuration.html#general-configuration

**Comment by jeffreyroberts** [comment]
I just got an email from someone who is having the same problem...

I do believe this is a bug in the system...

I was able to track this bug down to the Auth component, for me, I had to make sure that $this->Auth->user('id'), inside the AppController.beforeRender method, was not returning null to see the actual error, hope this helps

**Comment by ADmad** [comment]
If you end up generating recursive errors there's nothing the framework can do. Showing a minimal 500 error page is the only remaining possibility. The error logs would however contain details about initial error.

**Comment by haraldernst** [comment]
Same problem here. My Cakephp project works fine on local server. After deployment on another server all errors became "An Internal Server Error Occurred". 

It turned out that my deployment script (which compressed the complete project) stripped the folder __AND FILES__  with an _dev_.

When cakephp throws an error cakephp tries to load the file 

      vendor/cakephp/cakephp/src/Template/Layout/dev_error.ctp

And this file will never be found and invokes another error over and over again (I guess).

----

After uploading the project _without stripping *dev*_ everything works fine.

Here is my error: 
 
      zip -r project.zip project -x \*_playground\* -x \*.git\* -x \*dev\* -x \*.sass-cache\* 

Maybe you can check the existance of the critical error template ;-)
