### ISSUE TITLE
EncryptedCookieMiddleware Fails w/ DateTime::__construct(): Failed to parse time string (@+1 day) at position 0

### ISSUE THREAD

**Issue by jeffreyroberts** [cakephp/app#577]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 3.5.10
* Platform and Target: laravel valet, mysql, os x

### What you did
From the book on page https://book.cakephp.org/3.0/en/controllers/middleware.html#creating-middleware I saw that you are creating a cookie like so

        $response->cookie([
            'name' => '2fa',
            'value' => 'asdfasdf',
            'expire' => '+1 day'
        ]);

### What happened
500 error with...

    DateTime::__construct(): Failed to parse time string (@+1 day) at position 0 (@): Unexpected character

### What you expected to happen
A cookie to be created

**Comment by ADmad** [comment]
The manual example is incorrect, seems only numeric timestamp can be used as expiry value.

**Comment by markstory** [comment]
Closing as documentation has been updated.
