### ISSUE TITLE
Create a migration that can be copied to migration folder

### ISSUE THREAD

**Issue by mosaxiv** [cakephp/app#584]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

Create migration file from schema file.
https://github.com/cakephp/app/tree/master/config/schema

I think that it is troublesome to convert it to migration if it is only a schema file.

**Comment by dereuromark** [comment]
What is your use case - why do you have a schema file?
These days people only have migration files or fixture files representing the DB structure usually.

**Comment by mosaxiv** [comment]
When managing the DB with migration You need to create a migration file from `schema/sessions.sql`.

I thought that it would be better to prepare `schema/YYYYMMDDHHMMSS_Session.php`.

**Comment by dereuromark** [comment]
I see.
Maybe we should just convert them into (optional) migration files to be copied over in the actual config/Migrations dir to start with.
Or how do you currently initialize these schema files?

**Comment by mosaxiv** [comment]
I am considering the following
1. Create `schema/YYYYMMDDHHMMSS_Session.php`.
2. Create a shell to copy to `config/Migrations` dir.(e.g. `Migrations/20180315101010_Session.php`)

How about that?

**Comment by ADmad** [comment]
A shell to copy the file inside `Migrations` seems unnecessary. Just add a descriptive comment in the file stating that it should be copied/moved inside `Migrations` folder for it to be picked up by the migrations plugin.

**Comment by dereuromark** [comment]
Just put them in with a hardcoded timestamp of maybe beginning of this year and that should be fine then.
That would enable direct Copy and Paste usage.
I recommend prefixing the names with something unique, otherwise it can create conflicts with either app classes or other migration class names.

**Comment by mosaxiv** [comment]
thanks. I will create a PR :)
