### ISSUE TITLE
Error case reveals cake.css

### ISSUE THREAD

**Issue by dereuromark** [cakephp/app#586]
`href="/css/cake.css"/>` can be found on 404 pages by default.
I think we should rename cake.css to sth like style.css to make it a bit less obvious that this is a cake app.

Refs https://github.com/cakephp/cakephp/issues/11584

**Comment by markstory** [comment]
Ok.

**Comment by dereuromark** [comment]
Oops
I accidentally pushed directly into 3.next
https://github.com/cakephp/app/commit/56ba557c39c6a005fbd06d3a89c16efaf869936d
Can someone please verify?

**Comment by dereuromark** [comment]
Also, it seems 3.next is much behind master.
For people to try out the new core betas we should probably provide an up to date application as well.

**Comment by saeideng** [comment]
> Can someone please verify?

worked for me
