### ISSUE TITLE
This page isn’t working

### ISSUE THREAD

**Issue by haditrg92** [cakephp/app#588]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

![capture](https://user-images.githubusercontent.com/11014621/38319996-e9db54cc-3865-11e8-945e-1a66b78b1342.JPG)
when i upload to server certain page become (image above). I try many solution still not working.

I already this code in home.ctp still not working
if (!Configure::read('debug')):
throw new NotFoundException();
endif;

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks
