### ISSUE TITLE
bin/cake assumes the php executable is the CLI SAPI

### ISSUE THREAD

**Issue by Zuluru** [cakephp/app#589]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: Every release from 3.0 to at least 3.5.1
* Platform and Target: CentOS with cPanel and EasyApache

### What you did
Ran `bin/cake <shell_name>` from the cron.

### What happened
`bootstrap_cli.php` was not included.

### What you expected to happen
`bootstrap_cli.php` should be included.

`bin/cake` does `exec php`, and then `bootstrap.php` tests `$isCli = PHP_SAPI === 'cli';` to decide whether or not to include `bootstrap_cli.php` (among other things). But depending on the particular build options for PHP, it's possible that `php` is the CGI SAPI, and `php-cli` is needed to get the CLI SAPI. (In my case, presumably not an uncommon hosting environment for Cake users, `/usr/local/bin/php` is CLI, but `/usr/bin/php` is CGI, and the cron's PATH means that the latter is used there. `/usr/bin/php-cli` is a symlink to `/usr/local/bin/php`.)

I was able to fix this (once I eventually tracked down the problem) by changing `bin/cake` to `exec php-cli`, but it seems like it could be nice to build in a check for this. The output of `php -v` could be used, for example, or `echo "<?= PHP_SAPI ?>" | php` or the like.

**Comment by markstory** [comment]
Where would you see the proposed check being added?

**Comment by Zuluru** [comment]
It would presumably need to be in `bin/cake`, so that it runs the correct PHP executable. It might check `php`, `php-cli`, `/usr/local/bin/php` and exit with an error if none of them are CLI?

**Comment by markstory** [comment]
Ok. Any chance you would be willing to put together a pull request? I personally have not used an environment that has these requirements and don't think I am in a good position to fix it.

**Comment by Zuluru** [comment]
I'll see what I can come up with.
