### ISSUE TITLE
bootstrap.php contains HTTP_HOST reference which is generally considered insecure

### ISSUE THREAD

**Issue by driek** [cakephp/app#600]
This is a (multiple allowed):

* [x] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 3.6.0.
* Platform and Target: N.a.

### What you did
N.a.

### What happened
The `config/bootstrap.php` file in the CakePHP 3.0 application template project, sets the `fullBaseUrl` using (indirectly) `$_SERVER[HTTP_HOST]` in case it is not set.

### What you expected to happen
The above `$_SERVER['HTTP_HOST']` can be spoofed by headers in the request thus not being trustworthy. Instead `$_SERVER['SERVER_NAME']` would be a more secure option in my opinion. 
(I say more secure, because it also can be affected by request headers, but at least the Apache's `UseCanonicalName` can be used to override that and use the value specified at the `ServerName` directive instead)

**Comment by inoas** [comment]
Can you link your source that says one is insecure *and* the other is not, this one suggests both are:
https://expressionengine.com/blog/http-host-and-server-name-security-issues

**Comment by ADmad** [comment]
`'SERVER_NAME'` doesn't always match `'HOST_NAME'` even in cases where there is no tempering. We would end up with tons of `Cake generates incorrect URLs` type issues if we started using SERVER_NAME to generate full URLs.

You can just set `App.fullBaseUrl` yourself in `app.php` if you are concerned by `HOST_NAME` being spoofed.

**Comment by driek** [comment]
@inoas Please refer to the warning part at https://httpd.apache.org/docs/2.4/mod/core.html#usecanonicalname . When this setting is not used, I agree that `SERVER_NAME` can still be spoofed, hence I wrote **more** secure in the ticket.
@ADmad Fair enough, however would you consider to make a reference to this option somewhere in the documentation? Working with mainly the app.php, I never realized that the `fullBaseName` was overwritten in bootstrap.php. 
Don't get me wrong, I appreciate it is done somewhere in the source instead of the CakePHP directory inside `vendor` so I can edit it as you pointed out, however I just wish I knew sooner.
Also, just out curiosity, but do you know what the reason was for going with `HTTP_HOST` instead of `SERVER_NAME` ?

**Comment by dereuromark** [comment]
> Also, just out curiosity, but do you know what the reason was for going with HTTP_HOST instead of SERVER_NAME ?

There are also cases where you are behind a load balancer and the host is forwarded then inside that key for a reason.
It can have multiple reasons. If you want to make sure, always whitelist the incoming host values in your bootstrap process.

**Comment by ADmad** [comment]
> however would you consider to make a reference to this option somewhere in the documentation?

`App.fullBaseUrl` is already document [here](https://book.cakephp.org/3.0/en/development/configuration.html#general-configuration). It even suggests setting it manually to avoid the same thing you are concerned about `...or if you are concerned about people manipulating the Host header`.

Closing as there's nothing to be done here. Using `SERVER_NAME` instead of `HOST_NAME` is not an option and the fact that you can avoid relying on `HOST_NAME` by setting `App.fullBaseUrl` is already documented here.

**Comment by driek** [comment]
@dereuromark Thank you for your fast reply and clarification. It makes sense when there is a load balancer involved. For some reason I overlooked the possibility to check Host headers at a higher, ie webserver (or even .htaccess file if you have shared hosting). Quite informative, thank you.

**Comment by inoas** [comment]
@dereuromark yep we are relying on the load balancer setting the server name, too.
