### ISSUE TITLE
New plugin class causes some test weirdness

### ISSUE THREAD

**Issue by sdustinh** [cakephp/app#603]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

```bash
sdustinh@sdustinh:~/github/cakephp/app$ php --version
PHP 7.1.16-1+ubuntu16.04.1+deb.sury.org+1 (cli) (built: Apr  5 2018 08:47:00) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.1.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.1.16-1+ubuntu16.04.1+deb.sury.org+1, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.6.0, Copyright (c) 2002-2018, by Derick Rethans
sdustinh@sdustinh:~/github/cakephp/app$ mysql --version
mysql  Ver 14.14 Distrib 5.7.22, for Linux (x86_64) using  EditLine wrapper
sdustinh@sdustinh:~/github/cakephp/app$ composer show cakephp/*
cakephp/bake                1.7.2  Bake plugin for CakePHP 3
cakephp/cakephp             3.6.1  The CakePHP framework
cakephp/cakephp-codesniffer 3.0.3  CakePHP CodeSniffer Standards
cakephp/chronos             1.1.4  A simple API extension for DateTime.
cakephp/debug_kit           3.15.2 CakePHP Debug Kit
cakephp/elastic-search      0.3.5  An Elastic Search datasource and data mapper for CakePHP 3.0
cakephp/migrations          1.8.1  Database Migration plugin for CakePHP 3.0 based on Phinx
cakephp/plugin-installer    1.1.0  A composer installer for CakePHP 3.0+ plugins.
```

I was updating to 3.6 and have noticed some weirdness with using the new `Cake\Core\BasePlugin` class in the `Application::bootstrap()` process. By default, the `Application::bootstrap()` method does a `require_once` on the application `boostrap.php` and the `BasePlugin::bootstrap()` by default does a `require` on a plugin `boostrap.php`. If any plugins have a `Cache::setConfig()` or `Log::setConfig()` call, these will cause errors every time the test is run. This may be a matter of moving all of this into the new plugin classes. For now, I wrap them in `Cache::getConfig() === null` checks.

After I got past that, I found some strange scenarios. In `tests/bootstrap.php` there is a `require` call to the application `bootstrap.php`. This works fine for `TestCase` tests, but seems to cause many problems for `IntegrationTestCase` tests. One of the most noticeable problems is calls to `Configure::read()` will return empty data.

I couldn't decide if this was a framework issue or app skeleton issue because there seems to be a mixture of `require` and `require_once` calls in both repos that have caused these issues. I default to assuming the framework is the standard and the skeleton should follow that lead. I was patching all of these calls up but new issues relating to a mixture of `require` and `require_once` kept popping up so I figured it wouldn't hurt to open an issue.

Thanks!

**Comment by sdustinh** [comment]
Possibly relevant: https://secure.php.net/manual/en/function.require-once.php#121859

**Comment by markstory** [comment]
Replacing all the`require_once` calls with `require` isn't simple as application bootstrap file often define constants and configure cache/logging which would fail in a similar way to what you're having with plugins.

> If any plugins have a Cache::setConfig() or Log::setConfig() call, these will cause errors every time the test is run. This may be a matter of moving all of this into the new plugin classes. For now, I wrap them in Cache::getConfig() === null checks.

Conditionally defining log/caching should be what plugins do in general. Not doing that means the host application cannot re-configure the logging/caching the plugin uses.

**Comment by saeideng** [comment]
still relevant?
you can open issue  or a PR if you have solution
