### ISSUE TITLE
Enable session.strict_mode by default

### ISSUE THREAD

**Issue by dmromanov** [cakephp/app#609]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

Set session.strict_mode to `true` in boostrap.php. The option exists in PHP since version 5.5.2.
According to the docs, this option should be enabled for all applications.
http://php.net/manual/en/session.configuration.php#ini.session.use-strict-mode

**Comment by markstory** [comment]
Seems reasonable to me.
