### ISSUE TITLE
CSRF token mismatch While creating REST API

### ISSUE THREAD

**Issue by anehkumar** [cakephp/app#629]
HI, I am creating a REST API for Android and iOS using CakePHP 3. I am using CakePHP 3 JWT plugin but whenever I create post request from postman I get this error.

```
{
    "message": "CSRF token mismatch.",
    "url": "/api/login",
    "code": 403,
    "file": "/var/www/html/hospital/vendor/cakephp/cakephp/src/Http/Middleware/CsrfProtectionMiddleware.php",
    "line": 195
}
```
Can you please help to fix this. I am using latest version of CakePHP 3

**Comment by bravo-kernel** [comment]
The CSRF middleware found in your `Application.php` should not be used for APIs. Either remove it completely if your Cake app is API-only or disable it for your prefix. [This stackoverflow thread](https://stackoverflow.com/questions/47714940/cakephp-3-5-6-disable-csrf-middleware-for-controller) might help with the latter.
