### ISSUE TITLE
Exclude initial files from coverage report

### ISSUE THREAD

**Issue by dmromanov** [cakephp/app#637]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: master

File "src/Console/Installer.php" should be marked as excluded from unit-tests coverage report.
I'm not sure whether `src/Shell/ConsoleShell.php` should be excluded or not.

**Comment by markstory** [comment]
Seems reasonable. Did you intend to open a pull request on your fork?
