### ISSUE TITLE
Mark AppController as abstract

### ISSUE THREAD

**Issue by dmromanov** [cakephp/app#639]
This is a (multiple allowed):

* [ ] bug
* [ ] enhancement
* [x] feature-discussion (RFC)

`AppController` should be marked as `abstract` because it does not do any real action.

Some plugins might break.

**Comment by dereuromark** [comment]
Yeah, also stuff like https://github.com/dereuromark/cakephp-ide-helper/blob/master/src/Annotator/ControllerAnnotator.php#L139 would break.
Is there any benefit of this? Since the framework takes care that this specific controller can not be invoked directly.

**Comment by ADmad** [comment]
@dmromanov Have you faced any real issue by not having AppController declared as abstract?

**Comment by dmromanov** [comment]
This is a wish that I wanted to report a very long time, but did not have the opportunity.
Yes, I had problems with third-party code quality controls. I can't remember the specifics right now.
But I know for sure that there were problems when there were several Appcontrollers in the app. For Example: AppController ← AdminAppController ← RestAdminAppController & PublicAdminAppController. Without marking them as abstract ether CakePHP core or Bake tried to "use" them.

At the weekend I will try to recheck everything and publish the results.

But I suspect that they are unlikely to be confirmed now.

**Comment by ADmad** [comment]
Closing for reason stated by @dereuromark.
