### ISSUE TITLE
Limit composer.json suggest of phpunit to 5|6, note req'd by 'check' script

### ISSUE THREAD

**Issue by ewbarnard** [cakephp/app#647]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 3.6.5 (I think, installed via create-project --prefer-dist)
* Platform and Target: MacBook, MAMP Pro, PHP 7.2.1 (cli)

### What you did
composer check

### What happened
1. First time - phpunit not found
2. composer require --dev phpunit/phpunit (as suggested by "suggest")
3. PHP Fatal error: Class 'PHPUnit\Framework\BaseTestListener' not found - see https://github.com/cakephp/cakephp/issues/11732
4. Changed composer.json to "phpunit/phpunit": "^6" as per above issue 11732; composer update
5. "composer check" now runs green/clean

### What you expected to happen
We have two issues, both of which could be alleviated by placing clues in the "suggest"
documentation for phpunit/phpunit.

1. The "composer check" script requires that phpunit be installed.
2. CakePHP requires that we use phpunit version 5.x.x or 6.x.x.

I don't think we can explicitly suggest phpunit/phpunit:^6, but we could enhance the phrasing
in the comment string for the suggestion.

**Comment by dereuromark** [comment]
Sounds good, please make a PR.

**Comment by ewbarnard** [comment]
Will do, @dereuromark

**Comment by garas** [comment]
I think `phpunit/phpunit` should go to `require-dev`. App skeleton has `tests/`, has Composer "test" script, so I think is real dependency of app, testing with PHPUnit is highly promoted in docs.

And contrarily, I would move `mobiledetect/mobiledetectlib` to `suggest` and comment off related code in `bootstrap.php` leaving as sample for detectors. I don't see use for it as best practices recommends to use feature detection, not user agent. Also most CSS frameworks use responsive web design which don't need browser detection.

Also reason for `psy/psysh` is hidden, there is only single [tiny reference](https://book.cakephp.org/3.0/en/development/debugging.html#breakpoint) about it in docs. `bin/cake console` can be found by curiosity or file in `src/Shell`, shell has autodetect if Psysh is installed, so I would also move it to `suggest`.

**Comment by ewbarnard** [comment]
Going to require-dev does make sense to me and would remove the difficulty. Here's what I have as modified suggest:

 - phpunit/phpunit: Allows automated tests to be run without system-wide install. CakePHP supports phpunit versions 5.x and 6.x (composer require --dev phpunit/phpunit "^6"); the check/test composer scripts need phpunit.

By the way, I had trouble figuring out how to get composer to display the suggestion on my local cloned fork. I used "composer init" to create a dummy project, added a path repository pointing to my edited cakephp/app, required it as a dev dependency, and then "composer suggests -v" does show my new suggests text. Is there any place in the CakePHP ecosystem that I could document how to do that?

Meanwhile, what say you? Submit a PR for the "suggests" change, or PR making phpunit/phpunit:^6 a dev dependency?

**Comment by ewbarnard** [comment]
The "composer require" needs a colon : when specifying the version constraint; that's fixed in the potential PR.

**Comment by dereuromark** [comment]
We shouldnt overcomplicate the suggest texts.
As @garas proposed, a simple require-dev for phpunit suffices.

**Comment by ewbarnard** [comment]
Agreed. I tried various wordings, and all are ugly. Making it a require-dev is simple. I'll do the PR - only for the phpunit portion, NOT implementing @garas 's other suggestions.
