### ISSUE TITLE
integration of a framwork frontend as vuejs or react

### ISSUE THREAD

**Issue by bigsaala** [cakephp/app#652]
This is a (multiple allowed):

* [ ] bug
* [x ] enhancement
* [ ] feature-discussion (RFC)

Hello
Given the success of frontend frameworks like vuejs or react, I suggest you think about the fast integration of this type of framework. it will attract more people to use cakephp
thank you all

**Comment by cleptric** [comment]
I'm using Vue in multiple projects already. What kind of integration would you think of, that would make things easier?

**Comment by bigsaala** [comment]
@cleptric 
like laravel with a resource folder or the frontend framework is ready to be coded.

**Comment by cleptric** [comment]
Couldn't you just add vue via your favourite package manager and start coding right away?

**Comment by ADmad** [comment]
Requests / suggestions like this have already been answered to earlier.

There's currently nothing preventig one from using a front-end framework of their choice. We are not going to provide any sort of integration with any front-end framework. The JS ecosystem is too fickle and fast moving.

As a small team of volunteers we would like to just concentrate on the PHP code.
