### ISSUE TITLE
Testing scoped middleware 

### ISSUE THREAD

**Issue by liviascapin** [cakephp/app#659]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 3.7.1

Hi!
We noticed you moved the CSRF middleware from Application.php to routes.php in #630.
How can this be tested? What is the best approach to test whether the middleware is loaded and configured correctly for middleware registered in the routes (kind of like the ApplicationTest class)?

Maybe we could provide some tests for this, if you could point us in the right direction.

**Comment by markstory** [comment]
Are you looking to add tests to the skeleton or as part of your app?

Adding tests to the skeleton is a bit tricky as it does not come with any post specific actions.

In your application you can use integration tests to ensure that csrf is applied to the relevant actions.

**Comment by ravage84** [comment]
> Are you looking to add tests to the skeleton or as part of your app?

@markstory at best both.

Before the move, the existance and position of the CsrfProtectionMiddleware was tested in ApplicationTest. Now the app skeleton has a blind spot in this particular case. Thus, the code coverage kind of decreased.

**Comment by markstory** [comment]
The skeleton doesn't include any post actions making testing for CSRF a bit tricky.

**Comment by garas** [comment]
Posting to `PagesController` is possible, even if it doesn't handle submitted data.

Posting with/without CSRF token would end in different results.
