### ISSUE TITLE
webroot => public ?

### ISSUE THREAD

**Issue by dereuromark** [cakephp/app#663]
Other frameworks usually all use /public as primary webroot for nginx/apache
If we streamline ours here, we would make life/transition easier in general, also for cakebox and vagrant builds etc.

The others mention:

> configure your web server's document / web root to be the ROOT/`public` directory

Cake uses ROOT/`webroot` here as exception still.

Do we want to keep this or align/sync this to the standard?

**Comment by markstory** [comment]
I don't mind the change if we don't end up breaking existing applications that want to upgrade. Hopefully the `webroot` name is captured in a constant.

**Comment by ADmad** [comment]
Renaming the webroot folder requires renaming the constant `WWW_ROOT` in `paths.php` and changing the folder name for `App.webroot` config in `app.php`.

**Comment by ADmad** [comment]
But given that we use the name `webroot` for config keys and properties/method names in code I would rather keep the folder name same.

**Comment by dereuromark** [comment]
ok, we can revisit for 5.0 then.

**Comment by reloxx13** [comment]
i would prefer webroot because it will let the "webroot" folder at the bottom in the file/folder structure (ordered alphabetical). Calling it public would move it over the "src" folder.

I used cakephp for several projects and had not problems with using "webroot".

**Comment by gaurangkumar** [comment]
public / webroot / www / public_dir does not actually matter. For CakePHP i am happy with `webroot` and for Laravel and my own IronPHP using `public` .

**Comment by gaurangkumar** [comment]
but if you want to use `public`
`/config/paths.php` 
modify
```
/**
 * File path to the webroot directory.
 *
 * To derive your webroot from your webserver change this to:
 *
 * `define('WWW_ROOT', rtrim($_SERVER['DOCUMENT_ROOT'], DS) . DS);`
 */
define('WWW_ROOT', ROOT . DS . 'public' . DS);
```
and everything working fine.

but addition you also should change
`/config/app.php`
```
    'App' => [
        ------,
        'webroot' => 'public',
        'wwwRoot' => WWW_ROOT,
        ------
```

**Comment by groovenectar** [comment]
Guys, I just noticed this thread.

Please don't change `webroot`.

It's one of a few things that sets CakePHP apart from other frameworks, the webserver document root folder has a superior name if we're going to be using a subset of the English language for most of this stuff.

`webroot` is more descriptive than `public`. In this case the other frameworks are wrong and CakePHP is right. A close contender could be `htdocs`, but `public` is pretty low in the list of ideal names.

Other inferior frameworks doing it should never automatically be a reason to change something, in my opinion. The other frameworks should consider adapting `webroot`.

**Comment by markstory** [comment]
Given that people who really want to use public can do so with existing configuration options. I don't think there is a solid reason to change the default. Webroot is a clear concise name.
