### ISSUE TITLE
Bash CLI is broken when project's path contains spaces

### ISSUE THREAD

**Issue by dmromanov** [cakephp/app#687]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 2fda0d3e72d0a403280ff27f7843ddfa37b1909f
* Platform and Target: PHP 7.2, Ubuntu 19.04

### What you did
1. create a project and place it in a folder with spaces in it's path, e.g. `/home/example/example project/`
2. Launch console command from a project, whitch path contains spaces
3. Run from outside the project directory `/home/example/example project/bin/cake bake`

### What happened
```
Exception: Unknown command `cake bake`. Run `cake --help` to get the list of valid commands. in [/home/example/example project/vendor/cakephp/cakephp/src/Console/CommandRunner.php, line 346]
```

### What you expected to happen
Command run successfully
```
The following commands can be used to generate skeleton code for your application.

Available bake commands:

- all
- behavior
- cell
...
```

**Comment by markstory** [comment]
Pull request merged now.
