### ISSUE TITLE
App for CakePHP v3.8

### ISSUE THREAD

**Issue by BassemN** [cakephp/app#689]
Hello,

I noticed that there is no App release for CakePHP v3.8. I think you need to tag the master branch with `3.8.0` tag

Thanks

**Comment by saeideng** [comment]
latest tag `3.7.1` is fully compatible with cake 3.8 
yes will release new tag very soon

**Comment by BassemN** [comment]
The latest tag `3.7.1` is downloading CakePHP 3.7.* only https://github.com/cakephp/app/blob/3.7.1/composer.json#L9

**Comment by ADmad** [comment]
New `3.8.0` tagged.
