### ISSUE TITLE
Auto enable app_local.php and .env loading

### ISSUE THREAD

**Issue by inoas** [cakephp/app#707]
Can we have that? That would make creating docker compose environments for cakephp a breeze regarding database credentials, cache settings etc

**Comment by inoas** [comment]
Same question goes towards `//Configure::load('app_local', 'default');` why is this not the default?

**Comment by ADmad** [comment]
I don't see why anyone would use both .env files as well as environment based `app_*` files. So having both enabled by default would be quite silly IMO.

**Comment by inoas** [comment]
Much like requirements.php which can be removed one can remove the file_exists check / code for app_local.php and/or .env

That aside env files do not allow in any way calucations where as app_local.php does. But this is not about .env vs true env variables vs app_local vs boot parameters etc. but just about conventions:

**If you supply an app_local.php or .env file it should just work.** even both at the same time. where env sets the basics and app_local can overwrite.

**Comment by markstory** [comment]
Using environment variables will make deployments in kubernetes or other container based hosting simpler, while 'local' files make applications living on servers managed by ansible/puppet/chef easier. I'm not confident we can make a decision in either direction here, as each style is used for a different deployment style, and choosing only one will likely make the other harder, and choosing both adds complexity and opportunity for confusion. The current opt-in approach we have lets people choose the style they need.

**Comment by inoas** [comment]
@markstory though u cannot just composer create and work with that but have to fork the cakephp/app repo because app_local and/or .env must be loaded early in the bootstrap process.

Is the file_exists check really so expensive that this cannot be the default that you can opt-out of. Convention over configuration?

**Comment by inoas** [comment]
There are two PRs now, I hope that one will get accepted so that creating fresh cakephp projects via docker boxes is easier to do like so https://github.com/htstudios/cakephp-docker-compose-box/

**Comment by dereuromark** [comment]
PRs open
