### ISSUE TITLE
Think in micro

### ISSUE THREAD

**Issue by lpj145** [cakephp/app#708]
Yes i can see, cakephp is a a heavy height framework to solve some randomless problems... but sometimes i think, why cakephp not have a container ? psr-11 ? why cake is a powerfull and beautiful framework design not have a micro think ? yes, yours can have a some reasons and answers for this question, but, never be expressed on forum's or cake doc to developers... 

last week i worked on new cakephp skeleton to implement container and callable routes or actions routes using fastroute and aura.di and founded some facilities to do it, but a height job to couple bake and other somethings.

Please, sorry for my issue for nothing, i think this can be exposed or express to new or old cakephp users, this framework is good!

* [] bug
* [x] enhancement
* [x] feature-discussion (RFC)

**Comment by ADmad** [comment]
We don't need to try to cater to everyone's need :slightly_smiling_face:. Since CakePHP follows "convention over configuration" philosophy it works best when used as a whole. Yet there are various parts of the frameworks which are published as separate packages, for example `ORM`, `I18n` `Validation` etc. which you can use to build your own setup.

As for PSR-11 support it's already on the roadmap for CakePHP [4.1](https://github.com/cakephp/cakephp/wiki/4.1-Roadmap).

**Comment by lpj145** [comment]
hey @ADmad sorry for this issue, i know this is so difficulty to solve framework problems, new implementations, help others users, but i'm thinking almost year to produce new cake skeleton based on this solutions, your's provide some comunity or forum to tests possibilites on a new micro cake skeleton ? i think to remove all html provider's, features, all view's and produce a powerfull api first cake skeleton, easily auth, bake api,  documentation, and validations...

**Comment by ADmad** [comment]
Event our new authentication and authorization libs are framework agnostic.

**Comment by ADmad** [comment]
Such tickets just end up in bike shedding unless you have some concrete suggestions. If you just want the discuss the possibilities on how to the framework in a more decoupled way i suggest you use our [forum](https://discourse.cakephp.org/) instead.

**Comment by lpj145** [comment]
thanks for you attention, continue this discussion on forum.

**Comment by lpj145** [comment]
In some time i can end my skeleton, and post to community see, i have some lote ideas to cake, but i'm from brazil, and have some complications to express my opnion on english :(

Some question i trouble:

Why controller need to know if request is [POST, PUT, GET] if i defined on routes.php

alway's i bake model, controller, i lost all my job's.. hahah one day my TableClass have nice 800 lines... it's old!

TableClass have a validations definitions, yes validation is for request and model(ORM) but if is for two objects, why is not separator another location ?

About psr-11 a day i have a container on cake, i can build and automate a variety of logic's... ex: Table inject validations, or request inject validations, table automate build entity or many entities..

**Comment by lpj145** [comment]
Again! sorry for my bad english, continue practicing to expose my ideas!

**Comment by saeideng** [comment]
>Why controller need to know if request is [POST, PUT, GET] if i defined on routes.php

controller does not need to know if you define it explicit in routes.php 
but if you connect route with `connect()` maybe you need to know request mode

all these depends to you 

>continue this discussion on forum.

:+1:

**Comment by markstory** [comment]
I'm also working on getting the console libraries split out if you're looking for a small footprint CLI library.

**Comment by lpj145** [comment]
Is great @markstory, can you show me lib ?

**Comment by markstory** [comment]
@lpj145 ADmad gave a link earlier in the thread for the http package. There isn't a link for the console libraries yet as they aren't done.
