### ISSUE TITLE
loading cakephp file on webserver not working

### ISSUE THREAD

**Issue by GorgonMylar** [cakephp/app#715]
turn on xammp
sudo /opt/lampp/lampp start

cd to htdocs folder

composer create-project --prefer-dist cakephp/app donalds
 

navigating to 127.0.0.1/donalds
Fatal error: Uncaught Error: Class 'Cake\Http\Server' not found in /opt/lampp/htdocs/donalds/webroot/index.php:37 Stack trace: #0 {main} thrown in /opt/lampp/htdocs/donalds/webroot/index.php on line 37

**Comment by garas** [comment]
Check output of `composer create-project` if it finished without errors.
Check if `vendor/` directory exists and contains `vendor/cakephp/cakephp` subdirectory.

**Comment by GorgonMylar** [comment]
was i supposed to run the compser create-project in a certain place? I ran it in root and got this error


  [InvalidArgumentException]                                                  
  Composer could not find a composer.json file in /home/smiller               
  To initialize a project, please create a composer.json file as described i  
  n the https://getcomposer.org/ "Getting Started" section

**Comment by garas** [comment]
`composer create-project --prefer-dist cakephp/app donalds` should be called from `/opt/lampp/htdocs/`.

Later all commands should be called from `/opt/lampp/htdocs/donalds/`.

Try start over and check output for errors and if directories I said exists.

---

To get faster help with installing, try [Slack channel](https://cakesf.herokuapp.com/) or [#cakephp](https://webchat.freenode.net/?channels=#cakephp) on irc.freenode.net

**Comment by ADmad** [comment]
This is not a help forum. The ticket tracker is reserved for possible
bugs and feature enhancements to the CakePHP framework. If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:
 
[The CakePHP Manual](http://book.cakephp.org)
[The CakePHP online API](http://api.cakephp.org)
[CakePHP Official Forum](http://discourse.cakephp.org)
[Stackoverflow](http://stackoverflow.com/questions/tagged/cakephp)
[Slack channel](http://cakesf.herokuapp.com/)
 
or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.
 
Thanks!
