### ISSUE TITLE
cake4   add padding to paginate

### ISSUE THREAD

**Issue by LuizMarin** [cakephp/app#722]
This is a (multiple allowed):

* [ ] enhancement

![erro5-1](https://user-images.githubusercontent.com/50879411/67017840-b4481f00-f0d0-11e9-8ca3-9079966f4efb.png)

to 

![erro5-2](https://user-images.githubusercontent.com/50879411/67017454-3552e680-f0d0-11e9-874d-0c0ca4c63042.png)

**Comment by markstory** [comment]
Fixed in 9e49d4e419fbe8da6e48a26c5a8c43d707061887
