### ISSUE TITLE
Creating projects creates two sets of placeholder default credentials

### ISSUE THREAD

**Issue by othercorey** [cakephp/app#730]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 4.x

### What you did
Run project setup from tutorial.

```
php composer.phar create-project --prefer-dist cakephp/app bookmarker
```

### What happened
app_local.example.php is copied to app_local.php

Both app_local.php and app.php have full placeholder db credentials.

### What you expected to happen
Just app_local.php to have db credentials as users are pushed to use that file.

**Comment by othercorey** [comment]
@ADmad as discussed, if you want something to track.

**Comment by ADmad** [comment]
Besides db credentials there are various other config like for email which too are duplicated. This can lead to confusion in future as someone might make changes in `app.php` not realizing the defaults being overwritten in `app_local.php`.

There's should be no / minimal overlap of defaults set in the 2 files with config which generally vary depending upon environment being in `app_local.sample.php` and others in `app.php`.

**Comment by markstory** [comment]
Could we have only credentials and hosts/ports defined in app_local?

**Comment by othercorey** [comment]
If we move the defaults, I think app.php should contain a comment in each section just stating that the settings are in app_local.php and to use app.php for deploy.

You don't want just a blank app.php as that doesn't help a new user.

**Comment by ADmad** [comment]
> and to use app.php for deploy

No, `app.php` is commit to the repo so it should not have any credentials. The server should have it's own `app_local.php`.

**Comment by othercorey** [comment]
> > and to use app.php for deploy
> 
> No, `app.php` is commited to the repo so it should not have any credentials. The server should have it's own `app_local.php`.

Sorry, I meant deployed with ENV configuration that app

**Comment by dereuromark** [comment]
This is now resolved?
