### ISSUE TITLE
update composer install command for 3.x branch

### ISSUE THREAD

**Issue by andraskende** [cakephp/app#760]
https://github.com/cakephp/app/tree/3.x
A skeleton for creating applications with CakePHP 3.x.

Installation says:
composer create-project --prefer-dist cakephp/app

I think this should be changed to:
composer create-project --prefer-dist cakephp/app:3.x

also update on:
https://book.cakephp.org/3/en/installation.html

Thanks,
Andras

**Comment by saeideng** [comment]
would you like to open a PR on cakephp/docs ?
