### ISSUE TITLE
Memory leak?

### ISSUE THREAD

**Issue by swiffer** [cakephp/app#770]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 4.0.2
* Platform and Target: CLI, PHP 7.4.1 64bit NTS, Sqlite, Windows

### What you did
1. create project via `composer create-project --prefer-dist cakephp/app`
2. duplicate PagesControllerTest (this simulates having additional controller tested) to e.g. PagesControllerSecondTest
3. run PHPUnit `composer test`

### What happened
PHP times out and used excessive memory (multiple gb).

### What you expected to happen
Testsuite should complete just fine

This happens only when DebugKit is enabled. Even when not doing step 2 with DebugKit enabled the Testsuite takes Time: 16.85 seconds, Memory: 142.00 MB

With DebugKit disabled the Testsuite completes takes Time: 16.14 seconds, Memory: 14.00 MB

**Comment by garas** [comment]
DebugKit logs huge `tmp/debug_kit.sqlite` with huge data blobs for  `DebugKit.sql_log_panel`

Contents of  `tmp/debug_kit.sqlite` with after test suite with single copy of  `PagesControllerTest`:
![debugkit](https://user-images.githubusercontent.com/2265694/71645380-2d264280-2ce0-11ea-9937-eb259f7500c1.png)

Looks like memory grows exponentially as each test case includes all data from previous tests again, so the duplicate `PagesControllerTest` is just where memory reaches limit.

Memory grows ~2^7=256 times per copy of `PagesControllerTest`, so second copy would use 65K times more memory total.

SQL log contains queries of DebugKit itself (`CREATE TABLE "panels" ...`, `INSERT INTO panels`).

DebugKit should skip logging queries of itself?

**Comment by ADmad** [comment]
Shouldn't debugkit just skip all panels generation if app invoked from CLI?

**Comment by dereuromark** [comment]
Cli could be useful for sql queries. But thats already a separate ticket.
