### ISSUE TITLE
Suggested improvements for refreshed design 

### ISSUE THREAD

**Issue by mikebirch** [cakephp/app#771]
* CakePHP Application Skeleton Version: 4.0.2

The refreshed design is lighter and looks good, but I have noticed some issues:

- the color of anchor elements (including hover and focus styles) means that they're hard to distinguish from other text. Maybe use red and blue on hover like https://cakephp.org/ (for body text, not actions and menus).
- Raleway font is used for anchor elements, but Roboto for everything else. A lightweight design could look good by using one or the other, but doesn't need both.
- There is no spacing between labels and radio buttons

**Comment by cleptric** [comment]
@mikebirch Thanks for the feedback, I'll try to make some improvements here.

**Comment by ADmad** [comment]
@cleptric Can this be closed?

**Comment by cleptric** [comment]
IMO, yes.
Using different colours for the anchor tags might be a question of personal preference.
Removing the font is easy for a person to do.
I like the slight variation, so I would keep it as is.

**Comment by mikebirch** [comment]
The colours of anchor elements is an accessibility issue, not just personal preference, but I guess it’s easy enough to override.

**Comment by markstory** [comment]
@mikebirch Any chance you'd be up to open a pull request to pick a better link color?

**Comment by ndm2** [comment]
While we're at it, how about interchanging button colors, or at least using a different highlight color? Currently buttons are red when they're inactive, and grey when they're active, I find that rather counter intuitive.

**Comment by mikebirch** [comment]
> @mikebirch Any chance you'd be up to open a pull request to pick a better link color?

Yes, have had a go at it and tidied up the typography too. Raleway (400 and 700 weight) is included in src/templates/layout/default.php but Roboto is not. Headings are now set in Raleway and all text is 400 weight. Anchor elements are blue except for navigation, table headings and action links.
