### ISSUE TITLE
Missing milligram.min.css.map

### ISSUE THREAD

**Issue by allanmcarvalho** [cakephp/app#787]
This is a (multiple allowed):

* [x ] enhancement

As a suggestion, I think that is easy and a good idea put the `milligram.min.css.map` to remove the browsers warning in DevTools. I know that in most of cases, this theme is removed, but, I work with the principle of 'everything in your place, nothing missing'. Only one suggestion to make the skeleton more solid.

**Comment by ADmad** [comment]
Sounds good, would you like to open a pull request to add the file?

**Comment by dereuromark** [comment]
I just use AssetCompress with cssmin and jsmin filters, that removes it for me.
But for simplicity we can sure add it here.
