### ISSUE TITLE
Views Layout property

### ISSUE THREAD

**Issue by viniciusbig** [cakephp/app#799]
The View layout property is protected and can't be accessed directly.

https://github.com/cakephp/app/blob/c4d3644ccdee6ae057ed02988a572cfd7bfb5b2f/templates/Error/error400.php#L8
https://github.com/cakephp/app/blob/c4d3644ccdee6ae057ed02988a572cfd7bfb5b2f/templates/Error/error400.php#L11
https://github.com/cakephp/app/blob/c4d3644ccdee6ae057ed02988a572cfd7bfb5b2f/templates/Error/error500.php#L8
https://github.com/cakephp/app/blob/c4d3644ccdee6ae057ed02988a572cfd7bfb5b2f/templates/Error/error500.php#L11

We should change to 
$this->setLayout(...)

**Comment by dereuromark** [comment]
It can from inside the same class, here it is accessed properly through protected way. There is nothing wrong.

**Comment by othercorey** [comment]
@viniciusbig This is confusing because of the way View renders the template. 

https://github.com/cakephp/cakephp/blob/236664ba2434071f7c38ef336b23dd7258924abb/src/View/View.php#L1160

**Comment by viniciusbig** [comment]
If its ok, its ok!
Sorry!

My PHPStorm keep saying its wrong

![image](https://user-images.githubusercontent.com/191755/85337958-dee84400-b4b7-11ea-9d77-fab835971927.png)

Maybe I should config that it's right there.
I'll close this issue
