### ISSUE TITLE
Composer install/create-project error due to cakephp/bake and wyrihaximus/twig-view requirements

### ISSUE THREAD

**Issue by arturmamedov** [cakephp/app#808]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 4.1.1
* Platform and Target: Windows 10, PHP Version 7.2.4, Composer version 1.6.2 2018-01-05 15:28:41 tried also Composer version 1.10.13 2020-09-09 11:46:34

### What you did
I create project with composer that after try to install al the dependencies requiring-dev also

### What happened
Error is what heppened: `Your requirements could not be resolved to an installable set of packages.`

## Below entire message output:

$> composer create-project --prefer-dist cakephp/app cakephp4

Installing cakephp/app (4.1.1)
Installing cakephp/app (4.1.1): Downloading (100%)
Created project in cakephp4
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakephp/bake 2.0.10 requires wyrihaximus/twig-view ^5.0.1 -> satisfiable by wyrihaximus/twig-view[5.0.1].
    - cakephp/bake 2.0.3 requires wyrihaximus/twig-view ^5.0.1 -> satisfiable by wyrihaximus/twig-view[5.0.1].
    - cakephp/bake 2.0.4 requires wyrihaximus/twig-view ^5.0.1 -> satisfiable by wyrihaximus/twig-view[5.0.1].
    - cakephp/bake 2.0.5 requires wyrihaximus/twig-view ^5.0.1 -> satisfiable by wyrihaximus/twig-view[5.0.1].
    - cakephp/bake 2.0.6 requires wyrihaximus/twig-view ^5.0.1 -> satisfiable by wyrihaximus/twig-view[5.0.1].
    - cakephp/bake 2.0.7 requires wyrihaximus/twig-view ^5.0.1 -> satisfiable by wyrihaximus/twig-view[5.0.1].
    - cakephp/bake 2.0.8 requires wyrihaximus/twig-view ^5.0.1 -> satisfiable by wyrihaximus/twig-view[5.0.1].
    - cakephp/bake 2.0.9 requires wyrihaximus/twig-view ^5.0.1 -> satisfiable by wyrihaximus/twig-view[5.0.1].
    - cakephp/bake 2.1.0 requires cakephp/twig-view ^1.0 -> satisfiable by cakephp/twig-view[1.0.0, 1.0.1, 1.0.2, 1.1.0].
    - cakephp/bake 2.1.1 requires cakephp/twig-view ^1.0 -> satisfiable by cakephp/twig-view[1.0.0, 1.0.1, 1.0.2, 1.1.0].
    - cakephp/bake 2.1.2 requires cakephp/twig-view ^1.0 -> satisfiable by cakephp/twig-view[1.0.0, 1.0.1, 1.0.2, 1.1.0].
    - wyrihaximus/twig-view 5.0.1 requires twig/twig ^3.0 -> satisfiable by twig/twig[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5].
    - cakephp/twig-view 1.0.0 requires twig/twig ^3.0 -> satisfiable by twig/twig[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5].
    - cakephp/twig-view 1.0.1 requires twig/twig ^3.0 -> satisfiable by twig/twig[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5].
    - cakephp/twig-view 1.0.2 requires twig/twig ^3.0 -> satisfiable by twig/twig[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5].
    - cakephp/twig-view 1.1.0 requires twig/twig ^3.0 -> satisfiable by twig/twig[v3.0.0, v3.0.1, v3.0.2, v3.0.3, v3.0.4, v3.0.5].
    - twig/twig v3.0.5 requires php >=7.2.5 -> your PHP version (7.2.4) does not satisfy that requirement.
    - twig/twig v3.0.4 requires php >=7.2.5 -> your PHP version (7.2.4) does not satisfy that requirement.
    - twig/twig v3.0.3 requires php ^7.2.5 -> your PHP version (7.2.4) does not satisfy that requirement.
    - twig/twig v3.0.2 requires php ^7.2.5 -> your PHP version (7.2.4) does not satisfy that requirement.
    - twig/twig v3.0.1 requires php ^7.2.5 -> your PHP version (7.2.4) does not satisfy that requirement.
    - twig/twig v3.0.0 requires php ^7.2.9 -> your PHP version (7.2.4) does not satisfy that requirement.
    - Installation request for cakephp/bake ^2.0.3 -> satisfiable by cakephp/bake[2.0.10, 2.0.3, 2.0.4, 2.0.5, 2.0.6, 2.0.7, 2.0.8, 2.0.9, 2.1.0, 2.1.1, 2.1.2].

**Comment by dereuromark** [comment]
What composer version? Try latest.

**Comment by arturmamedov** [comment]
Sorry i now read the row `twig/twig v3.0.5 requires php >=7.2.5 -> your PHP version (7.2.4) does not satisfy that requirement.`

So i update PHP and all work fine!

###### Also for novice like me, don't forget enable intl in php.ini
