### ISSUE TITLE
Old composer.json when installing with composer

### ISSUE THREAD

**Issue by ironbone** [cakephp/app#813]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

When creating the application with 
composer create-project --prefer-dist cakephp/app appname

The old composer.json is taken. There is still inside of it 
`"post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump",`

**Comment by ADmad** [comment]
A new release has been done.
