### ISSUE TITLE
TypeError controller

### ISSUE THREAD

**Issue by dereuromark** [cakephp/app#833]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: latest master

### What you did
Someone accesses Pages as `/pages/`

### What happened

> [TypeError] Argument 1 passed to App\Controller\PagesController::display() must be of the type string, null given, called in /var/www/.../site/vendor/cakephp/cakephp/src/Controller/Controller.php on line 531 in /var/www/.../site/src/Controller/PagesController.php on line 73

### What you expected to happen
No internal server error but normal 404

Looking at the stacktrace we either need to make `public function display(string ...$path): ?Response` nullable
or we need to make sure a (casted) empty string is used instead of null?

**Comment by garas** [comment]
Fixed in https://github.com/cakephp/cakephp/pull/15445
