### ISSUE TITLE
add config/events.php with an example event listener

### ISSUE THREAD

**Issue by LordSimal** [cakephp/app#860]
* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 4.x

I just re-watched Jorge Gonzalez's CakeFest 2021 workshop and was wondering if we can/should a placeholder `config/events.php` and add a placeholder require to the `config/bootstrap.php` to let people know

* the event system exists at all,
* where event listeners can be placed/gathered in the first place to prevent implementation errors,
* how a simple event listener (maybe for the PagesController?) should look like + link to docs

Do we want to encourage people to use events or let them search/ask for the implementation themselves?

Was just curious what your opinions on that are. 😄

**Comment by markstory** [comment]
I am ambivalent to this. I don't personally use events much, but if it provides value to others I'm happy to move forwards.

**Comment by ADmad** [comment]
Not a fan of adding empty files to the skeleton. We could add a section in the manual instead.

**Comment by LordSimal** [comment]
To be fair I personally haven't implemented events in my own app as well because I haven't found the need to.
Maybe adjusting the book is better here indeed so the app template doesn't get bloated with files who are barely needed.
