### ISSUE TITLE
Fatal error: Uncaught Error: Class 'Cake\Utility\Security' not found in composer\src\Console\Installer.php:182

### ISSUE THREAD

**Issue by SerenityDevelopment** [cakephp/app#864]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 4.2.2
* Platform and Target: Windows 11 Pro

### What you did
I use PHPStorm as my IDE and so I created a new project for a CMS I'm developing. I put the name of my project, chose 'composer', cakephp/app and branch left at <default>. I then clicked create project.

### What happened
It begins the process of running the installer, once it reaches composer/tmp/cache/views directory the error happens.

### What you expected to happen
I expected the project to be created without any issue.

` Fatal error: Uncaught Error: Class 'Cake\Utility\Security' not found in C:\Users\schiz\PhpstormProjects\SerenityCMS\composer\src\Console\Installer.php:182
 Stack trace:
 #0 C:\Users\schiz\PhpstormProjects\SerenityCMS\composer\src\Console\Installer.php(64): App\Console\Installer::setSecuritySalt()
 #1 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(377): App\Console\Installer::postInstall()
 #2 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(236): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript()
 #3 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(117): Composer\EventDispatcher\EventDispatcher->doDispatch()
 #4 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/CreateProjectCommand.php(292): Composer\EventDispatcher\EventDispatcher->dispatchScript()
 #5 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/C in C:\Users\schiz\PhpstormProjects\SerenityCMS\composer\src\Console\Installer.php on line 182
 PHP Fatal error:  Uncaught Error: Class 'Cake\Utility\Security' not found in C:\Users\schiz\PhpstormProjects\SerenityCMS\composer\src\Console\Installer.php:182
 Stack trace:
 #0 C:\Users\schiz\PhpstormProjects\SerenityCMS\composer\src\Console\Installer.php(64): App\Console\Installer::setSecuritySalt()
 #1 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(377): App\Console\Installer::postInstall()
 #2 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(236): Composer\EventDispatcher\EventDispatcher->executeEventPhpScript()
 #3 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(117): Composer\EventDispatcher\EventDispatcher->doDispatch()
 #4 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/CreateProjectCommand.php(292): Composer\EventDispatcher\EventDispatcher->dispatchScript()
 #5 phar://C:/ProgramData/ComposerSetup/bin/composer.phar/src/Composer/Command/C in C:\Users\schiz\PhpstormProjects\SerenityCMS\composer\src\Console\Installer.php on line 182
 Failed to run 'create-project' command.

Composer packages were changed. PHPUnit config was updated according to composer.json`

**Comment by LordSimal** [comment]
I guess you didn't specify a version when creating the project with PHPStorm, right?

![image](https://user-images.githubusercontent.com/9105243/137445188-8974515d-479f-4b1f-9160-80879260e93e.png)

So you left `<default>` there which leads to CakePHP 4.2 being installed. Because I am not able to reproduce your problem.

**Comment by ADmad** [comment]
Creating a new app with `composer create-project cakephp/app myapp` works just fine. Your issue is related to PHPStorm and not CakePHP.

Please use one of our help forums for help with setting up the project using PHPStorm.
