### ISSUE TITLE
dd use vendor\sympfony\var_dumper\dump.php instead vendor\cakephp\cakephp\src\basic.php

### ISSUE THREAD

**Issue by nicokaiser79** [cakephp/app#877]
### Description

When I use the dd() method to debug some information, the dd method of vendor\sympfony\var_dumper\dump.php is used. This method has no output of the location of file and number of line who was dd in the code added.
It will better when the original method of cake dd vendor\cakephp\cakephp\src\basic.php will be used.
This method print the line and file where dd was added in the code.

### CakePHP Version

4.3.3.

### PHP Version

8.0

**Comment by dereuromark** [comment]
Can't we remove psy/psysh if we have the repl plugin ready?
Then people can opt in rather than opt out on it.

=> suggest

**Comment by ADmad** [comment]
Yup, we can remove cakephp/repl from the app's composer.json. Those who want it can install it themselves.
