### ISSUE TITLE
Locales path is wrong

### ISSUE THREAD

**Issue by hkosmidi** [cakephp/app#887]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)https://github.com/cakephp/app/blob/4.x/config/app.php#L67`

After a lot of digging on why my el_GR/default.po file wasn't working I found that config/app.php file has wrong locale path:

In https://github.com/cakephp/app/blob/4.x/config/app.php#L67

`'locales' => [RESOURCES . 'locales' . DS],`
should be
`'locales' => [ROOT . DS . 'resources' . DS. 'locales' . DS],`

**Comment by markstory** [comment]
But `RESOURCES . 'locales' . DS` is the same thing if you have the default constants defined https://github.com/cakephp/app/blob/6e5a382819596846e76accff5639259e64099d02/config/paths.php#L81
