### ISSUE TITLE
No installs cakephp/cakephp v4.4.4 (current)

### ISSUE THREAD

**Issue by zesschrno** [cakephp/app#905]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

### What you did
composer create-project --prefer-dist "cakephp/app:4.4.*" webservices

### What happened
installs cakephp/cakephp:4.4.1

### What you expected to happen
installs cakephp/cakephp:4.4.4

**Comment by cleptric** [comment]
It looks like you're mixing up the installation of the framework with the app skeleton (this repository).

Creating your app, will show you `Installing cakephp/app (4.4.1)`, which will install `Locking cakephp/cakephp (4.4.4)`.
