### ISSUE TITLE
Skip using ErrorHandlerMiddleware in cli mode

### ISSUE THREAD

**Issue by andrii-pukhalevych** [cakephp/app#911]
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 4.4.2.

[Using `ErrorHandlerMiddleware`](https://github.com/cakephp/app/blob/b8948f8aeb1d1d5991b9eb74d21c197ee7f26011/src/Application.php#L80) in `cli` mode seems to be not fully correct. 
It causes using of [`WebExceptionRenderer`](https://github.com/cakephp/cakephp/blob/45c91d7ed8a8804d20daf2e001e8e2b292aed77d/src/Error/Middleware/ErrorHandlerMiddleware.php#L58) in `cli` mode. 
In case of specifying `ConsoleErrorRenderer` in app config it blocks output to `stderror`.

Shouldn't we skip using `ErrorHandlerMiddleware` in `cli` mode?

**Comment by markstory** [comment]
> Shouldn't we skip using ErrorHandlerMiddleware in cli mode?

Probably, but the middleware changing the exception renderer is unexpected to me. Let me try and reproduce this.

**Comment by markstory** [comment]
Are you running into incorrect output in a command that you're writing, or is it another scenario? Do you have any tips or code on how I could reproduce the issue you're encountering.

**Comment by andrii-pukhalevych** [comment]
Seems I got this on some old app that didn't use regular way of console commands.
Instead, it accepts URL in command line - it was done to run app from both console and browser.
In `webroot/index.php` it has 
```
if (PHP_SAPI === 'cli') {
	$_SERVER['PHP_SELF'] = '/' . basename(__FILE__);
	$_SERVER['REQUEST_URI'] = $argv[1] ?? null;
}
```
and then
```
$response = $server->run();
if (PHP_SAPI === 'cli') {
	echo $response->getBody();
} else {
	$server->emit($response);
}
```
