### ISSUE TITLE
Error templates

### ISSUE THREAD

**Issue by ghost** [cakephp/app#992]
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Application Skeleton Version: 5.0.4.

### What happened
Error templates use `$error->params` which are protected. It would be better to use `$error->errorInfo` maybe...

templates/Error/error400.php line 27, 29
templates/Error/error400.php line 27, 29

**Comment by dereuromark** [comment]
See https://github.com/cakephp/app/pull/970 also
